// 장비 도트 파츠: 투구 / 망토 / 무기 / 방패. (SPEC §4.3~4.4)
// 순수 데이터 모듈 — document/window 를 건드리지 않는다.
//
// 앵커 규칙
//   helm_* : 하단 중앙(목) = JOINTS.head      -> ax = w/2, ay = h-1
//   cape_* : 상단 중앙      = JOINTS.chest     -> ax = 어깨 부착점, ay = 0 (몸통 뒤에 그려짐)
//   wpn_*  : 손잡이 그립점  = JOINTS.handFront (회전축이기도 하다)
//   shd_*  : 손잡이 중심    = JOINTS.handBack
//
// 무기는 전부 "세워 든 상태"(칼끝이 위 = y가 작은 쪽)로 그린다. 회전 0도가 기본 자세다.
// 문자: '.'투명 'o'외곽선 'm/M'금속 'l/L'가죽 'c/C'천 'a/A'강조 'w'하이라이트 'e'눈 'g/G'마력광
//
// ── 방향 가독성 규약 (가장 중요) ──────────────────────────────────────────
// 캐릭터는 오른쪽(+x)을 본다. 머리 조인트는 (16,14)다. 어느 머리 파츠든
//   * 눈(e)   은 y=7, x17~x18
//   * 얼굴 앞면(뺨·턱·목 앞) 은 y8~y14 의 x17 이상
// 에 놓이도록 그려져 있다. 그리기 순서가 머리 → 헤어 → 투구이므로 **투구가 이 자리를
// 덮으면 그대로 뒷모습이 된다.**
//
// 그래서 이 파일의 모든 helm_* 은 아래 한 가지 규칙을 지킨다.
//
//   ┌ y3~y6 : 정수리·이마는 통째로 덮는다. 앞쪽(x20~x21)으로 **이마 챙**이 1px 튀어나온다.
//   └ y7~y14: **x17 이상은 절대 덮지 않는다.** 뒤통수·귀·목덜미(x10~x16)만 덮는다.
//
// 즉 투구는 "뒤통수를 덮고 앞은 트인" 비대칭 실루엣이 되고, 그 트인 틈으로 눈과 옆뺨이
// 그대로 비친다. 통짜 투구(great/horned/mask)는 앞쪽 x19~x21 에 코·부리 가리개를
// 따로 띄워 붙여 얼굴 틈(x17~x18)을 사이에 둔 바이저 슬릿을 만든다.
//
// 망토는 어깨에서 **뒤(왼쪽)로 쏠리게** 그려 몸통에 가리지 않고 밖으로 삐져나오게 한다.
// 방패는 손잡이가 handBack 이지만 spritegen 의 SHIELD_OFFSET(+8) 로 몸 앞쪽에 놓인다.
// 방패면이 앞을 향해 보이도록 **뒤(x 작은 쪽)에 그림자 M/C, 앞(x 큰 쪽)에 하이라이트 w**,
// 가운데에 문양(a/A)을 넣는다. 세로 길이는 머리(y14 위)를 침범하지 않게 잡는다.
//
// 명암은 3단계다: 그림자(M/C/L/A) - 기본(m/c/l/a) - 하이라이트(w).
// 금속은 w를 넉넉히(모서리 한 줄), 천은 1~2px만 찍는다.

export const GEAR_PARTS = {
  // ── 투구 ──────────────────────────────────────────────────────────────────
  // 머리 파츠는 전부 x14~x21 폭의 좁은 옆얼굴이다. 투구는 그 뒤통수(x13~x16)만 물고
  // 앞(x17~)은 통째로 비운다. 챙만 x21~x22 까지 앞으로 튀어나온다.
  /** 철투구: 돔 + 이마 챙 + 귀를 덮는 뺨가리개. y7 부터 앞이 트여 눈·뺨·턱이 드러나고,
   *  뒤쪽 x11~x12 도 비워 뒷머리 한 줌이 투구 밖으로 삐져나온다. */
  // 96×120 네이티브
  helm_iron: {
    w: 39, h: 36, ax: 18, ay: 33, scale: 3,
    px: [
      '................ooooooooooo............',
      '..............ooMMmmmnnwwnmoo..........',
      '............oMMMmmmmnnnwwnnmmMo........',
      '...........oMMMMmmmmmnnnnwwnnmmMo......',
      '..........oMMMMMmmmmmmnnnnnwwnnmmMo....',
      '..........oMMMMMmmmmmmmnnnnnnwnnmmMo...',
      '.........oMMMMMMmmmmmmmnnnnnnnnnmmmMo..',
      '.........oMMMMMmmmmmmmmnnnnnnnnnmmMMo..',
      '.........oMMMnMMMMMnMMMMMnMMMMMnMMMMMo.',
      '.........oMMMMMMMmmo...........odmmnMo.',
      '.........oMMMMMMmmmo...........odmmnMo.',
      '.........oMMMMMmmmmo...........odmmnMo.',
      '........oMMMMMmmmmmo...........odmmmnMo',
      '........oMMMMMMmmmmo...........odmmmnMo',
      '........oooooooooooo...........oooooooo',
      '........oMMMmmno.......................',
      '........oMMMmmdo.......................',
      '........oMMmmmdo.......................',
      '.........oMMmmdo.......................',
      '.........oMMmmdo.......................',
      '.........oMnmmdo.......................',
      '.........oMmmmdo.......................',
      '..........oMmmdo.......................',
      '..........oMmmdo.......................',
      '..........oMmndo.......................',
      '..........oMmmdo.......................',
      '..........oooooo.......................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
    ],
  },

  /** 뿔투구: 앞뿔(x21~x23)이 뒤뿔(x10~x12)보다 훨씬 크고 앞으로 뻗는다 —
   *  뿔의 좌우 비대칭 자체가 방향 신호다. 얼굴 앞면은 전부 트여 있다. */
  // 96×120 네이티브
  helm_horned: {
    w: 48, h: 39, ax: 24, ay: 36, scale: 3,
    px: [
      '......ooo...................................ooo.',
      '.....obaAo.................................obaAo',
      '.....obaAo................................obaAo.',
      '......obaaAo..........oooooooooooo........obaAo.',
      '.......obaaAo.......ooMMmmmnnwwnnmoo.....obaaAo.',
      '.........obaaAAo..oMMMmmmmnnnnwwnnmmMo..obaaAo..',
      '..........obaaaAooMMMMmmmmmnnnnnwwnnmmMoobaaAAo.',
      '...........obaaAoMMMMMmmmmmmnnnnnnwnnmmMMobaaAAo',
      '...............oMMMMMMmmmmmmmnnnnnnnnnmmmMMo....',
      '...............oMMMMMmmmmmmmmmnnnnnnnnnmmmMMo...',
      '...............oMMMnMMMMMnMMMMMnMMMMMnMMMMMno...',
      '...............oMMMMMMMmmo...........odmmmnMo...',
      '...............oMMMMMmmmmo...........odmmmnMo...',
      '..............oMMMMMmmmmmo...........odmmmnMo...',
      '..............oMMMMMMmmmmo...........odmmmnMo...',
      '..............oooooooooooo...........oooooooo...',
      '..............oMMMmmmmmdo.......................',
      '..............oMMMnmmmmdo.......................',
      '..............oMMMmmmmmdo.......................',
      '..............oMMMmmmmmdo.......................',
      '..............oMMMmmnmmdo.......................',
      '..............oMMMmmmmmdo.......................',
      '..............oMMMmmmmmdo.......................',
      '..............oMMMmmmmmdo.......................',
      '..............oMMMmmmmmdo.......................',
      '...............oMMMmmmmdo.......................',
      '...............oMMMmmmmdo.......................',
      '...............oMMMmmmmdo.......................',
      '...............oMMnmmmmdo.......................',
      '...............oMMMmmmmdo.......................',
      '...............oMMMmmmmdo.......................',
      '...............oMMMmmmmdo.......................',
      '...............oMMMmmmmdo.......................',
      '................oMMmmmmdo.......................',
      '................oMMmmmmdo.......................',
      '................oMMmmmmdo.......................',
      '................oMMmmmmdo.......................',
      '................oMMmmmmdo.......................',
      '................oooooooo........................',
    ],
  },

  /** 대형 투구: 목까지 내려오는 통짜 투구. 앞쪽 x19~x22 에 부리 모양 코가리개를
   *  띄워 붙였다. 그 사이(x17~x18)가 세로 바이저 슬릿이 되어 눈과 뺨이 비친다. */
  // 96×120 네이티브
  helm_great: {
    w: 39, h: 39, ax: 18, ay: 36, scale: 3,
    px: [
      '..............ooooooooooo..............',
      '............oMMmmmnnwwnnmmMo...........',
      '...........oMMMmmmmnnnnwwnnmmMo........',
      '..........oMMMMmmmmmnnnnnwwnnmmmMo.....',
      '.........oMMMMMmmmmmmnnnnnnwnnmmmMMo...',
      '........oMMMMMMmmmmmmmnnnnnnnnnmmmMMo..',
      '........oMMMMMmmmmmmmmmnnnnnnnnnmmmMMo.',
      '.......oMMMMMMmmmmmmmmnnnnnnnnnmmmMMMo.',
      '.......oMMMnMMMMMnMMMMMnMMMMMnMMMMMnMo.',
      '.......oMMMMMMMmmmmmmmmnnnnnnnnmmmMMMo.',
      '.......oMMMMMMmmmmmmmmmnnnnnnnnnmmMMMo.',
      '.......oMMMMMmmmmmmmmmmnnnnnnnnnmmmMMo.',
      '.......oMMMMMmmmmmmmmmmnnnnnnnnnmmmMMo.',
      '.......oMMMMMMmmmmmmmmmmnnnnnnnnmmmMMo.',
      '.......oMMMMMMmmmMMMMMMnnnMMMMMnnnMMMo.',
      '.......oMMMMMmmmmmmmmmmmnnnnnnnnmmmMMo.',
      '.......oMMMMdddddddddddddddddddddddMMo.',
      '.......oMMMMdSSSSSSSSSSSSeexxSSddddMMo.',
      '.......oMMMMddSSSSSSSSSSSeeSSSdddddMMo.',
      '.......oMMMMdddddddddddddddddddddddMMo.',
      '.......oMMMMMMmmmmmmmmmnnnnnnnnnmmMMMo.',
      '.......oMMMMMmmmmmmmmmmnnnnnnnnnmmmMMo.',
      '.......oMMMMMmmmmmmmmmmnnnddnndnnmmmMo.',
      '.......oMMMMMMmmmmmmmmmnnnnnnnnnmmMMMo.',
      '.......oMMMMMmmmmmmmmmmnnnddnndnnmmmMo.',
      '.......oMMMMMMmmmmmmmmmnnnnnnnnnmmMMMo.',
      '.......oMMMMMmmmmmmmmmmnnnddnndnnmmmMo.',
      '........oMMMMMmmmmmmmmnnnnnnnnnmmMMo...',
      '........oMMMMMMmmmmmmmnnnnnnnnmmmMMo...',
      '........oMMMnMMMMMnMMMMMnMMMMMnMMMMo...',
      '........oMMMMMmmmmmmmmnnnnnnnnnmmMMo...',
      '..........oMMMMmmmmmnnnnnnnnmmMMo......',
      '..........oMMMMMmmmmmnnnnnnnmmmMo......',
      '..........oMMMMmmmmmmnnnnnnnmmMMo......',
      '............oMMMmmmmnnnnnmmMo..........',
      '............oMMMmmmmnnnnnmmMo..........',
      '............oMMMMmmmnnnnnmMMo..........',
      '............oMMMdmmmnnnndmMMo..........',
      '............ooooooooooooooooo..........',
    ],
  },

  /** 서클릿: 이마를 두르는 가는 띠 + 앞쪽 보석. 띠가 뒤(x13~x16)로만 한 단 더
   *  내려가 뒤통수를 물고, 앞은 눈 위에서 끊긴다. */
  // 96×120 네이티브
  helm_circlet: {
    w: 39, h: 36, ax: 18, ay: 33, scale: 3,
    px: [
      '.......................................',
      '.......................................',
      '.......................................',
      '..............................ooo......',
      '.............................oGgfo.....',
      '............................oGggffgo...',
      '............................oGGgffggo..',
      '.........ooooooooooooooooooooGGggooooo.',
      '.........oAAAaaagaaaabbbaaaagaaaaaaaAo.',
      '.........oAAAAaaaaaaabbbbbaaaaaaaaaAAo.',
      '.........oAAAAaagaaaabbbbaaaagaaaaAAAo.',
      '.........oAAAAAaaaaaaaaaaaaaaaaaaaAAAo.',
      '.........ooooooooooooooooooooooooooooo.',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
    ],
  },

  /** 후드: 천이 뒤통수·목덜미를 덮고 앞(x17~)이 통째로 트여 옆얼굴이 드러난다.
   *  트인 가장자리를 x16 에 세로로 딱 맞춰 얼굴선이 곧게 선다. */
  // 96×120 네이티브
  helm_hood: {
    w: 39, h: 36, ax: 18, ay: 33, scale: 3,
    px: [
      '................ooooooooooo............',
      '..............ooCCcccvvvcccoo..........',
      '............oCCCcccccvvvvvcccCo........',
      '...........oCCCCccccccvvvvvvcccCo......',
      '..........oCCCCCccccccvvvvvvvcccCCo....',
      '..........oCCCCCcccccccvvvvvvvcccCCo...',
      '.........oCCCCCCcccccccvvvvvvvvcccCCo..',
      '.........oCCCCCccccddddddddddddcccCCo..',
      '.........oCCCCCCcco............odCccvo.',
      '.........oCCCCCccco............odCccvo.',
      '.........oCCCCcccco............odCccvo.',
      '.........oCCCCCccco............odCccvo.',
      '........oCCCCCcccco............odCCccvo',
      '........oCCCCCCCcco............odCCccvo',
      '........ooooooooooo............oooooooo',
      '........oCCCcccvvdo............odCCccvo',
      '........oCCCcccvvdo............odCCccvo',
      '........oCCCcccvvdo............odCCccvo',
      '........oCCCccvvvdo............odCCccvo',
      '........oCCCcccvvdo............odCCccvo',
      '........oCCCcccvvdo............odCCccvo',
      '........oCCCcccvvdo............odCCccvo',
      '........oCCccccvvdo.............odCcvvo',
      '........oCCCcccvvdo.............odCcvvo',
      '........oCCCcccvvdo.............odCcvvo',
      '........oCCCcccvvdo.............odCcvvo',
      '........oCCCcvvvvdo.............ooooooo',
      '........oCCCcccvvdo....................',
      '........oCCCcccvvdo....................',
      '........oCCCcccvvdo....................',
      '........oCCCcccvvdo....................',
      '..........oCCcvvvdo....................',
      '..........oCCcvvvdo....................',
      '..........oCCcvvvdo....................',
      '..........oCCcvvvdo....................',
      '..........ooooooooo....................',
    ],
  },

  /** 마법사 고깔모자: 앞으로 살짝 기운 고깔 + 챙. 챙은 y6(눈 위)에서만 앞으로 뻗고
   *  뒤로는 어깨까지 늘어져 뒤통수를 덮는다 — 이 비대칭이 방향 신호다. */
  // 96×120 네이티브
  helm_wizard: {
    w: 54, h: 45, ax: 30, ay: 42, scale: 3,
    px: [
      '...............................oooo...................',
      '..............................oCccvo..................',
      '..............................oCCcvo..................',
      '.............................oCCcccvo.................',
      '.............................oCCcccvo.................',
      '............................oCCccccvvo................',
      '............................oCCccccvvo................',
      '...........................oCCCcccccvvo...............',
      '..........................oCCCccccccvvvo..............',
      '..........................oCCCccccccvvvo..............',
      '.........................oCCCCccccccvvvvo.............',
      '........................oCCCCcccccccvvvvvo............',
      '........................oCCCCcccccccvvvvvo............',
      '.......................oCCCCCcccccccvvvvvvo...........',
      '......................oCCCCCccccccccvvvvvvvo..........',
      '.....................oCCCCCCccccccccoggovvvvo.........',
      '....................oCCCCCCccccccccoGffgovvvvo........',
      '...................oCCCCCCCccccccccoGGggovvvvvo.......',
      '.............oCCCCCCCCccccccccccccccvvvvvvvvvvvvvvvvo.',
      '............oCCCCCCCCCcccccccccccccccvvvvvvvvvvvvvvvvo',
      '............oCCCCCCCCCCCCCCCCCCCCccccccccccccvvvvvvvvo',
      '............oooooooooooooooooooooooooooooooooooooooooo',
      '..................oCCCcccvvcdoddddddddddddddd.........',
      '..................oCCCcccvvcdoddddddddddd.............',
      '..................oCCCcccvvcdo........................',
      '..................oCCccccvvcdo........................',
      '..................oCCCcccvvcdo........................',
      '..................oCCCcccvvcdo........................',
      '..................oCCCcccvvcdo........................',
      '..................oCCCccvvvcdo........................',
      '..................oCCCcccvvcdo........................',
      '..................oCCCcccvvcdo........................',
      '..................oCCCcccvvcdo........................',
      '..................oCCCcccvvcdo........................',
      '....................oCCcvvvcdo........................',
      '....................oCCcvvvcdo........................',
      '....................oCCcvvvcdo........................',
      '....................oCCcvvvcdo........................',
      '....................oCCccvvcdo........................',
      '....................oCCcvvvcdo........................',
      '....................oCCcvvvcdo........................',
      '....................oCCcvvvcdo........................',
      '....................oCCcvvvcdo........................',
      '....................oCCcvvvcdo........................',
      '....................oooooooooo........................',
    ],
  },

  /** 왕관: 앞 첨두가 가장 높고 뒤로 갈수록 낮아진다. 띠가 뒤쪽(x13~x16)으로만
   *  두 단 더 내려와 뒤통수를 물기 때문에 앞얼굴만 남아 방향이 읽힌다. */
  // 96×120 네이티브
  helm_crown: {
    w: 39, h: 39, ax: 18, ay: 36, scale: 3,
    px: [
      '............oo......oo......oo.....oo..',
      '...........oao.....oao.....oao....oao..',
      '...........oabo....oabo....oabo...oabo.',
      '..........oabAo...oabAo...oabAo..ogbAo.',
      '..........oabbAo..oabbAo..oabbAo.oggbAo',
      '.........oaaabAo.oaaabAo.oaaabAooaaabAo',
      '.........oaaabAo.oaaabAo.oaaabAooaaabAo',
      '.........ooooooooooooooooooooooooooooo.',
      '.........oAAAaaagaaaabbbaaaagaaaaaaaAo.',
      '.........oAAAAaaaaaaabbbbbaaaaaaaaaAAo.',
      '.........oAAAAaagaaaabbbbaaaagaaaaAAAo.',
      '.........oAAAAAaaaaaaaaaaaaaaaaaaaAAAo.',
      '.........ooooooooooooooooooooooooooooo.',
      '.........oAAAaado......................',
      '.........oAAAaado......................',
      '.........oAAAaado......................',
      '.........oAAAaado......................',
      '.........oAAAaado......................',
      '.........oooooooo......................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
    ],
  },

  /** 깃털 투구: 정수리에 볏이 솟고 꽁지가 뒤로 흐른다. 철투구와 같은 규칙 —
   *  y7 부터 앞이 트여 눈·뺨·수염이 드러난다. */
  // 96×120 네이티브
  helm_plume: {
    w: 39, h: 42, ax: 18, ay: 39, scale: 3,
    px: [
      '..............oaaabbbbaaao.............',
      '..........oaaAabbbbbaaaao..............',
      '.......oaAAaabbbbaaaaAo................',
      '.....oAAaaaabbbaaaAAo..................',
      '...oAAaaaaabbaaAAo.....................',
      '..oAAAaaaaaabaaaAo.....................',
      '..oAAAaaaAAo....ooooooooooo............',
      '...oAAaAAo....ooMMmmmnnwwnmoo..........',
      '....oAAAo...oMMMmmmmnnnwwnnmmMo........',
      '.....oAAo..oMMMMmmmmmnnnnwwnnmmMo......',
      '......ooo.oMMMMMmmmmmmnnnnnwwnnmmMo....',
      '..........oMMMMMmmmmmmmnnnnnnwnnmmMo...',
      '.........oMMMMMMmmmmmmmnnnnnnnnnmmmMo..',
      '.........oMMMMMmmmmmmmmnnnnnnnnnmmMMo..',
      '.........oMMMnMMMMMnMMMMMnMMMMMnMMMMMo.',
      '.........oMMMMMMMmmmmmmmmnnnnnnnmmmMMo.',
      '.........oMMMMMMmmmmmmmmmnnnnnnnnmmMMo.',
      '.........oMMMMMmmmmmmmmmmnnnnnnnnmmmMo.',
      '........oMMMMMmmmmmmmmmmmnnnnnnnnnmmmMo',
      '........oMMMMMMmmmmmmmmmmmnnnnnnnnmmMMo',
      '........ooooooooooooooooooooooooooooooo',
      '........oMMMmmno.......................',
      '........oMMMmmdo.......................',
      '........oMMmmmdo.......................',
      '.........oMMmmdo.......................',
      '.........oMMmmdo.......................',
      '.........oMnmmdo.......................',
      '.........oMmmmdo.......................',
      '..........oMmmdo.......................',
      '..........oMmmdo.......................',
      '..........oMmndo.......................',
      '..........oMmmdo.......................',
      '..........oooooo.......................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
    ],
  },

  /** 가면 투구: 금속 가면 + 뒤통수를 감싸는 두정판. 가면 앞판(x19~x22)과 뒤통수 사이의
   *  세로 틈(x17~x18)으로 눈과 뺨이 번득인다. 턱 끝이 앞으로 뾰족하다. */
  // 96×120 네이티브
  helm_mask: {
    w: 39, h: 39, ax: 18, ay: 36, scale: 3,
    px: [
      '..............ooooooooooo..............',
      '............oMMmmmnnwwnnmmMo...........',
      '...........oMMMmmmmnnnnwwnnmmMo........',
      '..........oMMMMmmmmmnnnnnwwnnmmmMo.....',
      '.........oMMMMMmmmmmmnnnnnnwnnmmmMMo...',
      '........oMMMMMMmmmmmmmnnnnnnnnnmmmMMo..',
      '........oMMMMMmmmmmmmmmnnnnnnnnnmmmMMo.',
      '.......oMMMMMMmmmmmmmmnnnnnnnnnmmmMMMo.',
      '.......oMMMnMMMMMnMMMMMnMMMMMnMMMMMnMo.',
      '.......oMMMMMMMmmmmmmmmnnnnnnnnmmmMMMo.',
      '.......oMMMMMMmmmmmmmmmnnnnnnnnnmmMMMo.',
      '.......oMMMMMmmmmmmmmmmnnnnnnnnnmmmMMo.',
      '.......oMMMMMmmmmmmmmmmnnnnnnnnnmmmMMo.',
      '.......oMMMMMMmmmmmmmmmmnnnnnnnnmmmMMo.',
      '.......oMMMMMMMMMMMMMaaabbbaaaaaaaAAAo.',
      '.......oMMMMMmmmmmmmmAAaaaabbbaaaaaAAo.',
      '.......oMMMMMmmmmmmmmddddddddddddaAAAo.',
      '.......oMMMMMmmmmmmmmdSSSeexxSSddaAAAo.',
      '.......oMMMMMmmmmmmmmddSSeeSSSdddaAAAo.',
      '.......oMMMMMmmmmmmmmddddddddddddaAAAo.',
      '.......oMMMMMmmmmmmmmAAaaaabbbaaaaaAAo.',
      '.......oMMMMMmmmmmmmmAAaaaaabbaaaaaAAo.',
      '.......oMMMMMmmmmmmmmAAaaadbbdaaaaaAAo.',
      '.......oMMMMMmmmmmmmmAAaaaabbbaaaaaAAo.',
      '.......oMMMMMmmmmmmmmAAaaadbbdaaaaaAAo.',
      '.......oMMMMMmmmmmmmmAAaaaabbbaaao.....',
      '.......oMMMMMmmmmmmmmAAaaadbbo.........',
      '........oMMMMMmmmmmAAaaabo.............',
      '........oMMMMMMmmmmAAo.................',
      '........oMMMnMMMMMno...................',
      '........oMMMMMmmmmmo...................',
      '........oooooooooooo...................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
      '.......................................',
    ],
  },

  // ── 망토 (어깨에서 뒤쪽으로 쏠려 몸통 밖으로 나온다) ──────────────────────
  /** 짧은 망토: 앞어깨에 걸치고 뒤(왼쪽)로 삼각으로 퍼지는 숄.
   *  뒤로 흐르는 앞단(왼쪽 사선)에만 반사광 2px — 천은 하이라이트를 아껴 찍는다. */
  // 96×120 네이티브
  cape_short: {
    w: 48, h: 30, ax: 36, ay: 0, scale: 3,
    px: [
      '............................oooooooooooooooooo..',
      '...........................ovCvvcCvccCvcCCvCCo..',
      '.........................ooCCvccCvccCvvcCvvCCo..',
      '.......................oocCvvcCCvccCvvcCCvcCCo..',
      '.....................oocCCvccCCvccCCvccCCvcCCo..',
      '...................oocCCvvccCvvccCCvvcCCvvcCCo..',
      '.................oocCCvvccCCvvccCCvvccCCvvcCCo..',
      '...............ooccCCvvccCCvvccCCvvccCCvvccCCo..',
      '.............ooccCCvvcccCCvvccCCvvvccCCvvccCCo..',
      '............ovccCCvvvccCCvvcccCCvvccCCCvvccCCo..',
      '...........ovccCCCvvccCCCvvccCCCvvccCCCvvccCCo..',
      '..........ovccCCCvvcccCCvvcccCCvvvccCCvvvccCCo..',
      '.........ovccCCCvvcccCCvvvccCCCvvcccCCvvvccCCo..',
      '........ovcccCCvvvccCCCvvcccCCvvvccCCCvvcccCCo..',
      '.......ovcccCCvvvcccCCvvvccCCCvvvccCCCvvcccCCo..',
      '......ovcccCCCvvcccCCCvvcccCCCvvcccCCCvvcccCCo..',
      '.....ovcccCCCvvcccCCCvvvccCCCvvvcccCCvvvcccCCo..',
      '....ovcccCCCvvvcccCCvvvcccCCCvvvccCCCvvvcccCCo..',
      '...ovcccCCCvvvcccCCCvvvccCCCvvvcccCCCvvvcccCCo..',
      '...ovcccCCCvvvcccCCCvvvccCCCvvvcccCCCvvvcccCCo..',
      '..ovcccCCCvvvcccCCCvvvcccCCCvvvcccCCCvvvcccCCo..',
      '..ovcccCCCvvvcccCCCvvvcccCCCvvvcccCCCvvvcccCCo..',
      '.ovvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCvvvcccCCo..',
      '.ovvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCvvvcccCCo..',
      'ovvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCo..',
      'ovvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCo..',
      'occCCCCCCcccCCCCCCcccCCCCCCcccCCCCCCcccCCCCCCo..',
      'occCCCCCCcccCCCCCCcccCCCCCCcccCCCCCCcccCCCCCCo..',
      'oCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCo..',
      'oooooooooooooooooooooooooooooooooooooooooooooo..',
    ],
  },

  /** 긴 망토: 종아리까지 내려오는 정식 망토. 뒤로 길게 나부낀다. */
  cape_long: {
    w: 36, h: 64, ax: 33, ay: 0, scale: 3,
    px: [
      '..................ooooooooooooooo...',
      '.................occCCcccCCcccCdo...',
      '................ocvCCccvCCccvcCdo...',
      '...............ocvcCccccCCccccCCdo..',
      '...............ocvCCccccCCccccCCdo..',
      '...............ocvCCccccCCccccCCdo..',
      '..............ocvCCcccvcCCccvcCCdo..',
      '..............occCCcccvCCCccvcCCdo..',
      '.............occCCCccvcCCccccCCCdo..',
      '.............occCCcccvcCCccccCCCdo..',
      '..............ovcCCccccCCccccCCCdo..',
      '..............ovcCCccvcCCccccCCCdo..',
      '.............oAaCCcccvCCCccvcCCcCo..',
      '............oAaCCcccvcCCcccvcCCCCo..',
      '............oAaCCcccvcCCcccvCCCCCo..',
      '...........oAaCCcccvcCCcccvcCCcCCo..',
      '..........oAaCCcccvcdCCcccvcCCcCCo..',
      '.........oAaCCcccvcCdCcccvcCCcCCo...',
      '.........oAaCCcccvcCdCccvvcCCcCCo...',
      '.........oAaCCcccvcCdcccvcCCCcCCo...',
      '.........oAaCCcccvcdCcccvcCCCcCCo...',
      '........oAaCCcccvcCdCcccvcCCccCCo...',
      '........oAaCCcccvcCdCcccvcCCccCCo...',
      '........oAaCCcccvcCCCccvvcCCccCCo...',
      '.......oAaCCcccvcCCCcccvcCCCccCCo...',
      '........oAaCCccvvcCdcccvcCCCccCCo...',
      '........oAaCcccvvcCdcccvcCCCccCCo...',
      '........oAaCcccvvCCdcccvcCCCccCCo...',
      '........oAaCcccvcCCdccvcCCCccCCo....',
      '.......oAaCcccvcCCdcccvcCCCccCCo....',
      '......oAaCcccvcCCCdccvvCCCcccCCo....',
      '......oAaCcccvcCCCdccvcCCCcccCCo....',
      '.....oAaCcccvvcCCcccvvcCCCcccCCo....',
      '.....oAaCcccvcCCCcccvvcCCCcccCCo....',
      '.....oAaCcccvcCCdcccvvcCCccccCCo....',
      '.....oAaCcccvcCCdcccvvcCCcccvCCo....',
      '.....oAaccccvcCCdcccvcCCCcccvCCo....',
      '....oAaccccvcCCCdccvvcCCCcccvCCo....',
      '....oAacccvvcCCdcccvvcCCCcccvCCo....',
      '....oAacccvvcCCdcccvvcCCCcccvCCo....',
      '....oAacccvvcCCdcccvvCCCccccvCCo....',
      '....oAacccvcCCCcccvvcCCCcccvCCo.....',
      '....oAacccvcCCCcccvvcCCcccvvCCo.....',
      '....oAacccvcCCCdccvvCCCcccvvCCo.....',
      '....oAaccvvcCCCdccvcCCCcccvvCCo.....',
      '..ooacccvcCCCccdcvcCCCccccvcCCo.....',
      '..oAacccvcCCCccdcvcCCCccccvcCCo.....',
      '..oAaccvvcCCCcdcvvcCCCcccvvcCCo.....',
      '.oAaccvvcCCCccdcvvcCCCcccvvcCCo.....',
      '.oAaccvvcCCCccdcvcCCCCcccvvcCCo.....',
      '.oAaccvvcCCCcccvvcCCCccccvvcCCo.....',
      '.oAaccvvcCCCcccvvcCCCccccvcCCCo.....',
      '.oAaccvcCCCccdcvcCCCCcccvcCCCo......',
      'oAaccvcCCCCccdvvcCCCcccvvcCCCo......',
      'oAacvvcCCCCccdvvcCCCcccvvcCCCo......',
      '.oAacvvcCCCccdvvcCCCcccvvcCCCo......',
      '.oAacvvcCCCcdcvvcCCCcccvvcCCCo......',
      '.oAacvvCCCccdvvcCCCcccvvcCCCo.......',
      '.oAacvcCCCccdvvcCCCcccvvcCCCo.......',
      '..oCavvcCCCcccvcCCCcccvvcCCCo.......',
      '.oCCCCCCCCcccvvcCCCcccvCCCCCo.......',
      '..ooCCCCCCCCCCCCCCCCCCCCCCoo........',
      '....oooCCCCCCCCCCCCCCCCooo..........',
      '.......oooooooooooooooo.............',
    ],
  },

  /** 넝마 망토: 밑단이 찢겨 들쭉날쭉하다. */
  // 96×120 네이티브
  cape_tattered: {
    w: 50, h: 51, ax: 39, ay: 0, scale: 3,
    px: [
      '...............................oooooooooooooooooo.',
      '..............................ovCvvcCvccCvcCCvCCo.',
      '.............................ovCCvcCCvcCCvcCCvCCo.',
      '...........................ooCCvccCvvcCCvccCvvCCo.',
      '.........................oocCvvccCvvcCCvvcCCvcCCo.',
      '.......................oocCCvccCCvvcCCvvccCvvcCCo.',
      '.....................oocCCvvccCCvvcCCvvccCCvvcCCo.',
      '...................ooccCCvvccCCvvccCCvvccCCvvcCCo.',
      '.................ooccCCvvccCCvvcccCCvvccCCvvccCCo.',
      '...............ooccCCvvvccCCvvcccCCvvccCCCvvccCCo.',
      '.............ooccCCCvvcccCCvvcccCCvvvccCCvvvccCCo.',
      '............ovccCCCvvcccCCvvvccCCCvvcccCCvvvccCCo.',
      '...........ovcccCCvvvccCCCvvcccCCvvvccCCCvvcccCCo.',
      '..........ovcccCCvvvcccCCvvvccCCCvvvccCCCvvcccCCo.',
      '.........ovcccCCCvvcccCCCvvcccCCCvvcccCCCvvcccCCo.',
      '........ovcccCCCvvcccCCCvvvccCCCvvvcccCCvvvcccCCo.',
      '.......ovcccCCCvvvcccCCvvvcccCCCvvvccCCCvvvcccCCo.',
      '......ovcccCCCvvvcccCCCvvvccCCCvvvcccCCCvvvcccCCo.',
      '.....ovcccCCCvvvcccCCCvvvcccCCCvvvcccCCCvvvcccCCo.',
      '....ovvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCvvvcccCCo.',
      '....ovvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCvvvcccCCo.',
      '...ovvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCo.',
      '...ovvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCvvvcccCCCo.',
      '..ovvcccCCCvvvcccCCCvvvccccCCCvvvcccCCCvvvcccCCCo.',
      '..ovvcccCCCvvvcccCCCvvvccccCCCvvvcccCCCvvvcccCCCo.',
      '.ovvcccCCCvvvccccCCCvvvcccCCCvvvvcccCCCvvvcccCCCo.',
      '.ovvcccCCCvvvccccooCvvvcccCCCvvvvcccCCCvvvcccCCCo.',
      'ovvcccCCCvvvvccco..ovvccccCCCvvvcccCCCCvvvcccCCCo.',
      'ovvcccCCCvvvvccco..ovvccccCCCvvvcccCCCCvvvcccCCCo.',
      'ovvcccCCCvvvvccco..ovvccccCCCvvvcccCCCCvvvcccCCCo.',
      'ovvcccCCCvvvvcccCoovvvccccCCCvvvcccCCCCvvvcccCCCo.',
      'ovvcccCCCvvvvcccCCCvvvccccCCCvvvcccCCCCvvvcccCCCo.',
      'occcccCCCcccccccCCCcccccccCCCooooccCCCCccccccCCCo.',
      'occcccCCCcccccccCCCcccccccCCo....ocCCCCccccccCCCo.',
      'occcccCCCcccccccCCCcccccccCCo....ocCCCCccccccCCCo.',
      'occcccCCCcccccccCCCcccccccCCo....ocCCCCccccccCCCo.',
      'occCCCCCCccccCCCCCCcccCCCCCCo....oCCCCCcccCCCCCCo.',
      'occCCCCCCccccCCCCCCcccCCoooCCooooCCCCCCcccCCCCCCo.',
      'occCCCCCCccccCCCCCCcccCo...oCcccCCCCCCCcccCCCCCCo.',
      'occCCCCCCccccCCCCCCcccCo...oCcccCCCCCCCcccCCCCCCo.',
      'occooooCCccccCCCCCCcccCo...oCcccCCCCCCCcccCCCCCCo.',
      'oco....oCccccCCCCCCcccCo...oCcccCCCCCoooccCCCCCCo.',
      'oco....oCcccoooCCCCcccCo...oCcccCCCCo...ocCCCCCCo.',
      'oco....oCcco...oCCCcoooo...oCcccCCCCo...ocCCCCCCo.',
      'ooo....oCcco...oCCCo.......oCcccCoooo...ocCCCCCCo.',
      '.......oCcco...oCCCo.......oCccco.......ocCCCCooo.',
      '.......oCcco...oCCCo.......oCccco.......ocCCCo....',
      '.......ooooo...oCCCo.......oCccco.......ocCCCo....',
      '...............oCCCo.......oCccco.......oooooo....',
      '...............oCCCo.......oooooo.................',
      '...............ooooo..............................',
    ],
  },

  /** 날개 망토: 좌우로 활짝 펼쳐진 막 형태. */
  // 96×120 네이티브
  cape_wing: {
    w: 60, h: 48, ax: 30, ay: 0, scale: 3,
    px: [
      '...o.................ooooooooooooooooooo.................o..',
      '...oo................oCCCccccccccccvvvvo................oo..',
      '...oco...............oCCCcccccccvvvvvvvo...............ovo..',
      '...occo..............oCCCcccccccvvvvvvvo..............ovvo..',
      '...occcoo............oCCCcccccccvvvvvvvo............oovvvo..',
      '...occcCCo...........oCCCcccccccvvvvvvvo...........occvvvo..',
      '...occcCCCo..........oCCCcccccccvvvvvvvo..........occcvvvo..',
      '...occcCCCCo.........oCCCcccccccvvvvvvvo.........oCcccvvvo..',
      '...occcCCCCCoo.......oCCCcccccccvvvvvvvo.......ooCCcccvvvo..',
      '...occcCCCCCCco......oCCCcccccccvvvvvvvo......ovCCCcccvvvo..',
      '...occcCCCCCCcco.....oCCCcccccccvvvvvvvo.....ovvCCCcccvvvo..',
      '...occcCCCCCCccco....oCCCcccccccvvvvvvvo....ovvvCCCcccvvvo..',
      '...occcCCCCCCcccco...oCCCccccccccccvvvvo...ocvvvCCCcccvvvo..',
      '...occcCCCCCCccccco..oCCCccccccccccvvvvo..occvvvCCCcccvvvo..',
      '...occcCCCCCCcccccco.oCCCccccccccccvvvvo.occcvvvCCCcccvvvo..',
      '...occcCCCCCCccccccCoCccccccCCCCCcccvvvCoCcccvvvCCCcccvvvo..',
      '...occcCCCCCCccccccCCCccccccCCCCCcccvvvCCCcccvvvCCCcccvvvo..',
      '...occcCCCCCCccccccCCCccccccCCCCCcccvvvCCCcccvvvCCCcccvvvo..',
      '...occcCCCCCCccccccCCCccccccCCCCCcccvvvCCCcccvvvCCCcccvvvo..',
      '...occcCCCCCCccccccCCCccccccCCCCCcccvvvCCCcccvvvCCCcccvvvo..',
      '...occcCCCCCCccccccCCCccccccCCCCCcccvvvCCCcccvvvCCCcccvvvo..',
      '...occcCCCCCCccccccCCCccccccCCCCCcccvvvCCCcccvvvCCCcccvvvo..',
      '...occcCCCCCCccccccCCCccccccCCCCCcccvvvCCCcccvvvCCCcccvvvo..',
      '...occcCCCCCCccccccCCCccccccCCCCCcccvvvCCCcccvvvCCCcccvvvo..',
      '....ooCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCoo...',
      '......oocCccCCCcccccCCCcccccCCCCCcccvvCCCcccvvCCCcccvoo.....',
      '........occccCCCcccccCCcccccCCCCCccvvvCCcccvvCCCccvvo.......',
      '.........occccCCCccccCCCccccCCCCCccvvCCCccvvCCCccvvo........',
      '..........occccCCcccccCCccccCCCCCccvvCCcccvvCCccvvo.........',
      '...........occccCCccccCCccccCCCCCccvvCCccvvCCccvvo..........',
      '............oCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCo...........',
      '.............occcCCccccCCccccCCCccvvCCccvvCCccvo............',
      '..............occcCCcccCCccccCCCccvvCCcvvCCccvo.............',
      '...............occcCCcccCCcccCCCccvCCccvCCccvo..............',
      '................occcCcccCCcccCCCccvCCcvvCccvo...............',
      '.................occCCcccCcccCCCcvvCccvCCcvo................',
      '..................oCCCCCCCCCCCCCCCCCCCCCCCo.................',
      '...................occCcccCccCCCcvCccvCcvo..................',
      '....................occCccCccCCCcvCcvCcvo...................',
      '.....................occCccCccCcvCcvCcvo....................',
      '......................ocCccCccCcvCcvCco.....................',
      '.......................ocCcCccCcvCvCco......................',
      '........................oCCCCCCCCCCCo.......................',
      '.........................occCcCcCvco........................',
      '..........................oCccCvcCo.........................',
      '...........................oCCCCCo..........................',
      '............................ocCco...........................',
      '.............................ooo............................',
    ],
  },

  // ── 무기 (칼끝이 위, 앵커 = 그립) ────────────────────────────────────────
  /** 한손검: 곧은 양날검. 날 중앙에 반사광 한 줄, 가드는 강조색. */
  wpn_sword: {
    w: 32, h: 54, ax: 9, ay: 40, scale: 3,
    px: [
      '..............................oo',
      '.............................ono',
      '............................omno',
      '...........................omnno',
      '..........................ommno.',
      '.........................ommnno.',
      '........................ommMMno.',
      '.......................ommMMnno.',
      '......................oMmmMMnno.',
      '......................ommMMnno..',
      '.....................oMmmMMnno..',
      '.....................ommMMnnno..',
      '....................ommmMMnnno..',
      '...................oMmmMMnnno...',
      '...................ommmMnnnno...',
      '..................oMmmMMnnno....',
      '..................ommMMnnwno....',
      '.................oMmmMMnnwo.....',
      '.................ommMMnnwwo.....',
      '................oMmmMMnnwo......',
      '................ommMMnnwo.......',
      '...............oMmmMMnnno.......',
      '..............oMmmMMnnno........',
      '..............ommmMMnnno........',
      '.............oMmmMMnnno.........',
      '.............ommMMnnnno.........',
      '............oMmmMMnnno..........',
      '............ommMMnnwwo..........',
      '...........oMMmMMnnwo...........',
      '...........oMMMMnnwo............',
      '.........ooAMMMmmnwo............',
      '........oAAAaammmmo.............',
      '.........oAaaaaammo.............',
      '.........oAaaaabbo..............',
      '..........oaaaabbo..............',
      '.........olllabbbbo.............',
      '.........oLllkoooo..............',
      '........olLLko..................',
      '........olllLo..................',
      '.......oLLlko...................',
      '.......olLLo....................',
      '......olllko....................',
      '.....oLLLko.....................',
      '.....olllLo.....................',
      '....oLllko......................',
      '....olLLko......................',
      '....ollko.......................',
      '..ooaalko.......................',
      '.oAAaabo........................',
      'oAAaaabo........................',
      'oAaaabbo........................',
      '.oaaabbo........................',
      '.ooabbo.........................',
      '...ooo..........................',
    ],
  },

  /** 대검: 폭 넓고 긴 양손검. */
  // 96×120 네이티브
  wpn_greatsword: {
    w: 23, h: 78, ax: 11, ay: 66, scale: 3,
    px: [
      '...........o...........',
      '..........owo..........',
      '.........omnwo.........',
      '.........omnnwo........',
      '........oMmnnwo........',
      '........oMmMnnno.......',
      '.......oMmmdMnnno......',
      '.......ommmdMnnwo......',
      '......oMmmdMmnnno......',
      '......oMmmdMmnnwo......',
      '.....oMMmmdMmnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMMnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMmnnnno.....',
      '.....oMMmmdMmnnnwo.....',
      '.....oMmmmdMmnnwwo.....',
      '.....oMMmmdMmnnnwo.....',
      '.....oMMmmdMmnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMMnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMmnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMMnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMmnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMMnnnno.....',
      '.....oMMmmdMmnnnwo.....',
      '.....oMmmmdMmnnwwo.....',
      '.....oMMmmdMmnnnwo.....',
      '.....oMMmmdMMnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMmnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMMnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMmnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMMnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMmnnnno.....',
      '.....oMMmmdMmnnnwo.....',
      '.....oMmmmdMmnnwwo.....',
      '.....oMMmmdMmnnnwo.....',
      '.....oMMmmdMmnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMMnnnno.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMmnnnwo.....',
      '.....oMmmmdMmnnnno.....',
      '.....oMMmmdMMnnnno.....',
      '.....oMMmmdMMnnnMo.....',
      '......oMmmdMMnnno......',
      '......oMMmdMMnnno......',
      '.ob...oMMmdMMnnno...bo.',
      'oAaaaooMMmMMMnnnooaabbo',
      'oAAAaaaaaaaaaaabbbbbbbo',
      'oAAAAaaaaaaaaaabbbbbbbo',
      '.oAAAaaaaaaaaaabbbbbbo.',
      '...oAAaaaaaaaaabbbbo...',
      '......oAAaaaabbbo......',
      '.......oLLlllkko.......',
      '.......oLllllkko.......',
      '.......oLdlllkdo.......',
      '.......oLLlllkko.......',
      '.......oLllllkko.......',
      '.......oLdlllkdo.......',
      '.......oLLlllkko.......',
      '.......oLllllkko.......',
      '.......oLdlllkdo.......',
      '.......oLLllkkko.......',
      '.....oAAaaaaabbbbo.....',
      '....oAAAaaaaaabbbbo....',
      '....oAAAAaaaaabbbbo....',
      '.....oAAAaaaabbbbo.....',
      '.......ooooooooo.......',
    ],
  },

  /** 카타나: 외날 도. 등날은 어둡고 날은 하얗게 선다. 원형 츠바. */
  // 96×120 네이티브
  wpn_katana: {
    w: 20, h: 64, ax: 9, ay: 55, scale: 3,
    px: [
      '........o...........',
      '.......owo..........',
      '......onwo..........',
      '.....omnwo..........',
      '....omnnwo..........',
      '...oMmnnwo..........',
      '...oMmmnnwo.........',
      '...oMmMnnwo.........',
      '...ommMnnwo.........',
      '...oMmMnnno.........',
      '...ommMnwwo.........',
      '...oMmMnnwo.........',
      '...ommMnnno.........',
      '...oMmMnnwo.........',
      '...ommMnnwo.........',
      '...oMmMnnno.........',
      '...ommMnwwo.........',
      '...oMmMnnwo.........',
      '...ommMnnno.........',
      '...oMmMnnwo.........',
      '....ommMnnwo........',
      '....oMmMnnno........',
      '....ommMnwwo........',
      '....oMmMnnwo........',
      '....ommMnnno........',
      '....oMmMnnwo........',
      '....ommMnnwo........',
      '....oMmMnnno........',
      '....ommMnwwo........',
      '....oMmMnnwo........',
      '....ommMnnno........',
      '.....oMmMnnwo.......',
      '.....ommMnnwo.......',
      '.....oMmMnnno.......',
      '.....ommMnwwo.......',
      '.....oMmMnnwo.......',
      '.....ommMnnno.......',
      '.....oMmMnnwo.......',
      '.....ommMnnwo.......',
      '.....oMmMnnno.......',
      '.....ommMnwwo.......',
      '......oMmMnnwo......',
      '......ommMnnno......',
      '......oMmMnnwo......',
      '......ommMnnwo......',
      '.....oAaaaabbbo.....',
      '.....oAAaaabbbo.....',
      '.....oAaaaabbbo.....',
      '..oAAaaaaaaaabbbbo..',
      'oAAAaaaaaaaaaabbbbbo',
      'oAAAAaaaaaaaaabbbbbo',
      '..oAAAaaaaaabbbbbo..',
      '......oCcccvvo......',
      '......odCckvdo......',
      '......oCcccvvo......',
      '......oCccvvvo......',
      '......odCckvdo......',
      '......oCcccvvo......',
      '......oCccvvvo......',
      '......odCckvdo......',
      '......oCcccvvo......',
      '......oCCccvvo......',
      '.....oAAaabbbbo.....',
      '......oooooooo......',
    ],
  },

  /** 레이피어: 아주 가는 찌르기 검 + 바구니형 손잡이. */
  // 96×120 네이티브
  wpn_rapier: {
    w: 21, h: 64, ax: 10, ay: 51, scale: 3,
    px: [
      '..........o..........',
      '.........owo.........',
      '.........onwo........',
      '........oMmno........',
      '........oMmwo........',
      '........oMMno........',
      '........oMmno........',
      '........ommwo........',
      '........oMmno........',
      '........oMmwo........',
      '........oMMno........',
      '........oMmno........',
      '........ommwo........',
      '........oMmno........',
      '........oMmwo........',
      '........oMMno........',
      '........oMmno........',
      '........ommwo........',
      '........oMmno........',
      '........oMmwo........',
      '........oMMno........',
      '........oMmno........',
      '........ommwo........',
      '........oMmno........',
      '........oMmwo........',
      '........oMMno........',
      '........oMmno........',
      '........ommwo........',
      '........oMmno........',
      '........oMmwo........',
      '.......oMMmnno.......',
      '.......oMmmnwo.......',
      '.......oMMmnno.......',
      '.......oMmmnno.......',
      '.......oMMmnno.......',
      '.......oMmmnwo.......',
      '.......oMMmnno.......',
      '.......oMmmnno.......',
      '.......oMMmnno.......',
      '.......oMmmnwo.......',
      '.......oMMmnno.......',
      '.......oMmmnno.......',
      '.......oMMmnno.......',
      '.......oMMMnno.......',
      '..oAAaaaaaaabbbbbbo..',
      '..oAAAaaaaaabbbbbbo..',
      '...oo..oAaabbo..oAbo.',
      '..obbo.oLllkko..oAbo.',
      '.oa..booLLlkko..oAbo.',
      '.oA..boodLlkdo..oAbo.',
      '.oA..booLllkko..oAbo.',
      '..oAbo.oLLlkko..oAbo.',
      '...oo..odLlkdo..oAbo.',
      '.......oLllkko..oAbo.',
      '.......oLLlkko.oAbo..',
      '.......odLlkdo.oAbo..',
      '.......oLllkkooAbo...',
      '.......oLLlkkooAbo...',
      '.......oLLlkkoAbo....',
      '......oAAaaaabbbo....',
      '.....oAAaaaaabbbbo...',
      '.....oAAAaaaabbbbo...',
      '......oAAaaabbbbo....',
      '.......ooooooooo.....',
    ],
  },

  /** 단검: 짧은 양날 단도. */
  // 96×120 네이티브
  wpn_dagger: {
    w: 17, h: 36, ax: 8, ay: 25, scale: 3,
    px: [
      '........o........',
      '.......owo.......',
      '......omwwo......',
      '......omnwwo.....',
      '.....oMmnnwo.....',
      '.....oMmmnnwo....',
      '....oMmmMnnwo....',
      '....ommmMnnwo....',
      '....oMmmMMnwo....',
      '....oMmmMnnno....',
      '....ommmMnnwo....',
      '....oMmmMnwwo....',
      '....oMmmMnnwo....',
      '....ommmMnnwo....',
      '....oMmmMMnwo....',
      '....oMmmMnnno....',
      '....ommmMnnwo....',
      '....oMmmMnwwo....',
      '....oMMmMMnno....',
      '..oAAaaaaabbbbo..',
      '.oAAAaaaaaabbbbo.',
      '..oAAAaaaabbbbo..',
      '.....oAaabbo.....',
      '.....oLllkko.....',
      '.....oLLlkko.....',
      '.....odLlkdo.....',
      '.....oLllkko.....',
      '.....oLLlkko.....',
      '.....odLlkdo.....',
      '.....oLllkko.....',
      '.....oLLlkko.....',
      '...oAAaaaabbbo...',
      '..oAAaaaaabbbbo..',
      '...oAAaaabbbbo...',
      '....oAAaabbbo....',
      '.....ooooooo.....',
    ],
  },

  /** 쌍단검: 손을 사이에 두고 두 자루를 나란히 쥔다. 날 밑동에 그림자 한 줄. */
  // 96×120 네이티브
  wpn_twindagger: {
    w: 29, h: 36, ax: 14, ay: 25, scale: 3,
    px: [
      '.....o.................o.....',
      '....omo...............owo....',
      '...oMmmo.............omwwo...',
      '..oMmmMno...........oMmnnwo..',
      '.oMMmmMnno.........oMmmMnnwo.',
      '.oMmmmMnno.........ommmMnnwo.',
      '.oMMmmMMno.........oMmmMnwwo.',
      '.oMmmmMnno.........oMmmMnnno.',
      '.oMMmmMnno.........ommmMnnwo.',
      '.oMmmmMMno.........oMmmMMnwo.',
      '.oMMmmMnno.........oMmmMnnwo.',
      '.oMmmmMnno.........ommmMnnwo.',
      '.oMMmmMMno.........oMmmMnwwo.',
      '.oMmmmMnno.........oMmmMnnno.',
      '.oMMmmMnno.........ommmMnnwo.',
      '.oMmmmMMno.........oMmmMMnwo.',
      '.oMMmmMnno.........oMmmMnnwo.',
      '.oMmmmMnno.........ommmMnnwo.',
      'oAAAaaaaabo.......oAAaaaaabbo',
      'oAAAAaaaabo.......oAAAaaaabbo',
      '.oAAaaaabo.........oAAaaabbo.',
      '..oLLllko...........oLllkko..',
      '..oLLLlko...........oLLlkko..',
      '..odLllko...........odLlkdo..',
      '..oLLllko...........oLllkko..',
      '..oLLLlko...........oLLlkko..',
      '..odLllko...........odLlkdo..',
      '..oLLllko...........oLllkko..',
      '..oLLLlko...........oLLlkko..',
      '..odLllko...........odLlkdo..',
      '.oAAaaaabo.........oAAaaabbo.',
      'oAAAaaaaabo.......oAAaaaaabbo',
      'oAAAAaaaabo.......oAAAaaabbbo',
      '.oAAaaaabo.........oAAaaabbo.',
      '..oAAaabo...........oAaabbo..',
      '..ooooooo...........ooooooo..',
    ],
  },

  /** 손도끼: 한손용 도끼. 날 바깥쪽 초승달에 반사광. */
  // 96×120 네이티브
  wpn_axe: {
    w: 21, h: 48, ax: 9, ay: 33, scale: 3,
    px: [
      '........ooo..........',
      '.......oLlko.........',
      '......oLLllko........',
      '......oLLllko........',
      '......onnnmMMo.......',
      '.....omnnnmMMnwo.....',
      '....oMmnnnmMdmnnwo...',
      '....oMmnnmMdMmmnnwo..',
      '...oMMmnnmMdMmmmnnwo.',
      '...oMMmnnmMdMmmmnnwwo',
      '...oMmmnnnmdMmmnnnwwo',
      '...oMMmnnmMdMmmnnnwwo',
      '...oMMmmnmMdMmmmnnwwo',
      '...oMMMmnmMdMMmmnnwwo',
      '...oMMMmmmMdMMmmnnwo.',
      '....oMMmmMdMMmmmnwo..',
      '....oMMmMdMMmmmnwo...',
      '.....oMMdMMmmnwo.....',
      '......oMdMMmno.......',
      '......oMMdMMo........',
      '......oAaabao........',
      '......oAAaabo........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLlkko........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLLLLo........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLLLLo........',
      '......oLLllko........',
      '......oLLlkko........',
      '......oLLllko........',
      '......oLLLLLo........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLLLLo........',
      '......oLLllko........',
      '......oLLllko........',
      '......oAaabao........',
      '......oAAaabo........',
      '......oAAabbo........',
      '.......oAabo.........',
      '........oao..........',
      '........ooo..........',
    ],
  },

  /** 대도끼: 거대한 양손 도끼. 날이 자루 바깥(오른쪽)으로만 뻗어 얼굴을 가리지 않는다. */
  // 96×120 네이티브
  wpn_greataxe: {
    w: 27, h: 72, ax: 6, ay: 54, scale: 3,
    px: [
      '.....ooo...................',
      '....oLlko..................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllkodMMmnwo..........',
      '...oLLllkodMMmmmnnnwo......',
      '...oLLllkodMMmmmnnnmmnwo...',
      '...oLLllkodMMmmmnnnmmmmnwo.',
      '...oLLllkodMMmmmnnnmmmmnnwo',
      '...oLLllkodMMMmmnnmmmmnnnwo',
      '...oLLllkodMMmmnnnmmmmmnnwo',
      '...oLLllkodMMmmmnnnmmmmnwwo',
      '...oLLllkodMMmmmnnmmmmmnnwo',
      '...oLLllkodMMMmmnnnmmmmnnwo',
      '...oLLllkodMMMmmmnnmmmmnnwo',
      '...oLLllkodMMMMmmnnmmmmnnwo',
      '...oLLllkodMMMMmmnnmmmmnwo.',
      '...oLLllkodMMMMmmnnmmmnwo..',
      '...oLLllkodMMMMmmnnmmnwo...',
      '...oLLllkodMMMMmmnnmwo.....',
      '...oLLllkodMMMMmmnwo.......',
      '...oLLllkodMMMmwo..........',
      '...oLLllkodMmo.............',
      '...oAAaabo.................',
      '...oAAabbo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLlkko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLlkko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLlkko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oAAaabo.................',
      '...oAAabbo.................',
      '....oAabo..................',
      '.....oao...................',
      '.....ooo...................',
    ],
  },

  /** 철퇴: 가시 달린 타격 머리. */
  // 96×120 네이티브
  wpn_mace: {
    w: 21, h: 51, ax: 9, ay: 30, scale: 3,
    px: [
      '.........o...........',
      '........oao..........',
      '.......oAabo.........',
      '......oAAabbo........',
      '......oMmnnno........',
      '.....oMMmnnnno.......',
      '....oMMmmnnnwno......',
      '....oMMmmnnwwno......',
      '...oMMMmmnnnwwno.....',
      '...odMMmmmnnnwno.....',
      '..oodMMMmmmnnnnooo...',
      '.oAodMMMmmmmnnnobbo..',
      'oAAoddMMMmmmnnnobbbo.',
      '.oAodMMMMmmmmnnoAAo..',
      '..oodMMMMMmmmnnooo...',
      '....odMMMMmmmno......',
      '....oMMMMMmmmno......',
      '.....oMMMMmmmo.......',
      '......oMMMmmo........',
      '......oAAaabo........',
      '......oAAabbo........',
      '......oLLllko........',
      '......oLLlkko........',
      '......oLLllko........',
      '......oLLLLLo........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLLLLo........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLLLLo........',
      '......oLLllko........',
      '......oLLlkko........',
      '......oLLllko........',
      '......oLLLLLo........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLLLLo........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLllko........',
      '......oLLLLLo........',
      '......oLLllko........',
      '......oAAaabo........',
      '......oAAabbo........',
      '.......oAabo.........',
      '........oao..........',
      '........ooo..........',
    ],
  },

  /** 워해머: 네모난 육중한 머리 + 긴 자루. */
  // 96×120 네이티브
  wpn_hammer: {
    w: 27, h: 60, ax: 6, ay: 45, scale: 3,
    px: [
      '.....ooo...................',
      '....oLlko..................',
      '...oLLllko.................',
      '...oLLllko.oooooooooooooo..',
      '...oLLllkoonnnnwwnnnnnnwno.',
      '...oLLllkomnnnnnwnnnnnnnwno',
      '...oLLllkoMAabdmnnnnmmMnwwo',
      '...oLLllkodAabdMmnnnmmMnnwo',
      '...oLLllkodAabdMmmnnmmMnnwo',
      '...oLLllkodAAadMmmnnmmMnnwo',
      '...oLLllkodAabdMmmmnnmMnnwo',
      '...oLLllkodAabdMMmmnnmMmnwo',
      '...oLLllkodAabdMMmmmnmMmnwo',
      '...oLLllkodAAadMMmmmnmMmnno',
      '...oLLllkodAAadMMMmmmmMmnno',
      '...oLLllkodAAadMMMmmmMMmmno',
      '...oLLllkodAAAdMMMMmmMMmmno',
      '...oLLllkodAAAdMMMMMMMMMmmo',
      '...oLLllkooAAAdMMMMMMMMMMo.',
      '...oLLllko.oooooooooooooo..',
      '...oAAaabo.................',
      '...oAAabbo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLlkko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLlkko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oLLLLLo.................',
      '...oLLllko.................',
      '...oLLllko.................',
      '...oAAaabo.................',
      '...oAAabbo.................',
      '....oAabo..................',
      '.....oao...................',
      '.....ooo...................',
    ],
  },

  /** 창: 나뭇대에 나뭇잎형 창날. */
  // 96×120 네이티브
  wpn_spear: {
    w: 15, h: 78, ax: 7, ay: 60, scale: 3,
    px: [
      '.......o.......',
      '......owo......',
      '......ono......',
      '.....oMmno.....',
      '.....oMmno.....',
      '.....oMmwo.....',
      '....oMMmnno....',
      '....oMMmnno....',
      '....oMMmnwo....',
      '...oMMmmwnno...',
      '...oMMmmmnno...',
      '...oMMmmmnwo...',
      '..oMMMmmwnnno..',
      '..oMMMmmmnnno..',
      '..oMMMmmmnwno..',
      '..oMMMmmmnnno..',
      '...oMMmmmnno...',
      '...oMMmmwnno...',
      '....oMMmnno....',
      '....oMMmmno....',
      '.....oMmno.....',
      '.....oMmno.....',
      '.....oMMno.....',
      '.....oAaabo....',
      '....oAAaabbo...',
      '....oAaaabbo...',
      '....oAAaabbo...',
      '.....oAaabo....',
      '.....oLllko....',
      '.....oLllko....',
      '.....oLLlko....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....oLllko....',
      '.....oLLlko....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....oLllko....',
      '.....oLLlko....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....oLllko....',
      '.....oLLlko....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....oLllko....',
      '.....oLLlko....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....oLllko....',
      '.....oAaabo....',
      '.....oAabbo....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oAabbo....',
      '.....oAaabo....',
      '.....oAabbo....',
      '....oAAaabbo...',
      '....oAaaabbo...',
      '....oAaabbbo...',
      '....oooooooo...',
    ],
  },

  /** 파이크: 창보다 훨씬 긴 장창. 밀집대형용. */
  // 96×120 네이티브
  wpn_pike: {
    w: 15, h: 84, ax: 7, ay: 66, scale: 3,
    px: [
      '.......o.......',
      '......owo......',
      '......ono......',
      '......ono......',
      '......omo......',
      '.....oMmwo.....',
      '.....oMmno.....',
      '.....oMmno.....',
      '.....oMmno.....',
      '.....oMmwo.....',
      '.....oMmno.....',
      '....oMMmnno....',
      '....oMMmnno....',
      '....oMMmnwo....',
      '....oMMmnno....',
      '....oMMmmno....',
      '....oMMmnwo....',
      '....oMMmnno....',
      '...oMMmmwnno...',
      '...oMMmmmnno...',
      '...oMMmmmnwo...',
      '...oMMmmmnno...',
      '...oMMmmwnno...',
      '...oMMmmmnno...',
      '....oMMmnno....',
      '....oMMmnwo....',
      '....oMMmmno....',
      '.....oMmno.....',
      '.....oMmno.....',
      '.....oMmwo.....',
      '.....oMmno.....',
      '.....oMMno.....',
      '.....oAaabo....',
      '....oAAaabbo...',
      '....oAaaabbo...',
      '....oAAaabbo...',
      '....oAaaabbo...',
      '.....oAaabo....',
      '.....oLllko....',
      '.....oLllko....',
      '.....oLLlko....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....oLllko....',
      '.....oLLlko....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....oLllko....',
      '.....oLLlko....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....oLllko....',
      '.....oLLlko....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....oAaabo....',
      '.....oAabbo....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oLlkko....',
      '.....oLllko....',
      '.....odLlLo....',
      '.....oAabbo....',
      '.....oAaabo....',
      '.....oLllko....',
      '.....oAabbo....',
      '....oAAaabbo...',
      '....oAaaabbo...',
      '....oAaabbbo...',
      '....oooooooo...',
    ],
  },

  /** 미늘창: 찌르기 첨두 + 자루 바깥쪽에 붙은 도끼날. */
  // 96×120 네이티브
  wpn_halberd: {
    w: 24, h: 78, ax: 3, ay: 60, scale: 3,
    px: [
      '...o....................',
      '..owo...................',
      '..ono...................',
      '.oMwno..................',
      '.oMmno..................',
      '.oMmno..................',
      'oMMmnno.................',
      'oMMmnwo.................',
      'oMMmnno.................',
      'oMMmmno.................',
      'oMMmmno.................',
      'oMMMmno.................',
      'oAaaabo.................',
      'oAAaabo.................',
      'oMMmmnooooooooo.........',
      'oMMmmnodMMmMmmnooo......',
      'oMMmmnodMMmmMmmmnnoo....',
      'oLLlkkodMMMmmMmmmnnnoo..',
      'oLLllkoddMMmmMMmmmnnwwo.',
      'oLLllkoddMMmmmMmmmmnnwwo',
      'oLLllkoddMMmmmMmmmmnnwwo',
      'oLLlkkoddMMmmmMmmmmnnwwo',
      'oLLllkoddMMmmmMmmmmnnwwo',
      'oLLllkoddMMmmMMmmmnnwwo.',
      'oLLllkoddMMmmMMmmmnnwwo.',
      'oLLlkkodMMMmmMmmmnnnwo..',
      'oLLllkodMMmmMMmmmnnwo...',
      'oLLllkodMMmmMmmmnnoo....',
      'oLLllkodMMmMmmnnoo......',
      'oLLlkkodMmmmmnoo........',
      'oMMmmnodMmmmoo..........',
      'oMMmmnodmmoo............',
      'oMMmmnodmo..............',
      'oMMmmnooo...............',
      'oAAaabo.................',
      'oAaaabo.................',
      'oLLllko.................',
      'oLLllko.................',
      'oLLlkko.................',
      'oLLllko.................',
      'oLLllko.................',
      'oLLllko.................',
      'oLLlkko.................',
      'oLLllko.................',
      'oLLllko.................',
      'oLLllko.................',
      'oLLlkko.................',
      'oLLllko.................',
      'oLLllko.................',
      'oAaaabo.................',
      'oAAaabo.................',
      'odLLlLo.................',
      'oLllkko.................',
      'oLLllko.................',
      'odLLlLo.................',
      'oLllkko.................',
      'oLLllko.................',
      'odLLlLo.................',
      'oLllkko.................',
      'oLLllko.................',
      'odLLlLo.................',
      'oLllkko.................',
      'oLLllko.................',
      'odLLlLo.................',
      'oLllkko.................',
      'oLLllko.................',
      'odLLlLo.................',
      'oLllkko.................',
      'oLLllko.................',
      'odLLlLo.................',
      'oAAaabo.................',
      'oAaaabo.................',
      'oLLllko.................',
      'oLLlkko.................',
      'oAAaabo.................',
      'oAaaabbo................',
      'oAaabbbo................',
      'oooooooo................',
    ],
  },

  /** 낫: 자루 위쪽에서 앞쪽(오른쪽)으로 크게 휘어 나가는 날. */
  // 96×120 네이티브
  wpn_scythe: {
    w: 36, h: 72, ax: 9, ay: 54, scale: 3,
    px: [
      '...................oooooo...........',
      '......ooooooo...ooonwwwwwooo........',
      '......oMMmmno.oonnnnnnnnnwwnoo......',
      '......oMMmnnooMMnnnmmmmmmnnnnno.....',
      '......oMMmmnodMnmmmmmmmmmmmmnnno....',
      '......oAaaaboMmmmmmMMMMMMmmmmmno....',
      '......oAAaabommmMMMwwwwwwMMMmmmno...',
      '......oMMmmnomMMwwwoooooowwwMMmmo...',
      '......oMMmnnoMnnooo......ooowwMmno..',
      '......oMMmmnonoo............oowMmo..',
      '......oAAaaboo................onMo..',
      '......oAaaabo..................onMo.',
      '......oLLllko...................ono.',
      '......oLLllko....................oo.',
      '......oLLllko.....................o.',
      '......oLLlkko.....................o.',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLlkko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLlkko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLlkko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLlkko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLlkko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLlkko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oLLllko.......................',
      '......oAaaabo.......................',
      '......oAAaabo.......................',
      '......odLLlLo.......................',
      '......oLllkko.......................',
      '......oLLllko.......................',
      '......odLLlLo.......................',
      '......oLllkko.......................',
      '......oLLllko.......................',
      '......odLLlLo.......................',
      '......oLllkko.......................',
      '......oLLllko.......................',
      '......odLLlLo.......................',
      '......oLllkko.......................',
      '......oLLllko.......................',
      '......odLLlLo.......................',
      '......oLllkko.......................',
      '......oLLllko.......................',
      '......odLLlLo.......................',
      '......oLllkko.......................',
      '......oLLllko.......................',
      '......odLLlLo.......................',
      '......oAAaabo.......................',
      '......oAaaabo.......................',
      '......oLLllko.......................',
      '......oLLlkko.......................',
      '......oAabbbo.......................',
      '.....oAAaaabbo......................',
      '.....oAaaabbbo......................',
      '.....ooooooooo......................',
    ],
  },

  /** 활: 앞쪽으로 불룩한 목재 활대와 팽팽한 시위. */
  // 96×120 네이티브
  wpn_bow: {
    w: 18, h: 57, ax: 12, ay: 27, scale: 3,
    px: [
      '.....oo...........',
      '....obao..........',
      '....oaao..........',
      '...woAao..........',
      '...w.oLko.........',
      '...w.oLko.........',
      '...w..oLlko.......',
      '...w..oLlko.......',
      '...w...oLlko......',
      '...w...oLlko......',
      '...w...oLlko......',
      '...w....oLlko.....',
      '...w....oLlko.....',
      '...w....oLlko.....',
      '...w.....oLlko....',
      '...w.....oLlko....',
      '...w.....oLlko....',
      '...w......oLlko...',
      '...w......oLlko...',
      '...w......oLlko...',
      '...w......oLlko...',
      '...w.......oLlko..',
      '...w.......oLlko..',
      '...w.......oLlkko.',
      '...w.......oAaabbo',
      '...w.......oAaabbo',
      '...w.......oLllkko',
      '...w.......oLllkko',
      '...w.......odLllko',
      '...w.......oLllkko',
      '...w.......odLllko',
      '...w.......oLllkko',
      '...w.......odLllko',
      '...w.......oLllkko',
      '...w.......odLllko',
      '...w.......oAaabbo',
      '...w.......oAaabbo',
      '...w.......oLllko.',
      '...w.......oLlko..',
      '...w.......oLlko..',
      '...w......oLlko...',
      '...w......oLlko...',
      '...w......oLlko...',
      '...w......oLlko...',
      '...w.....oLlko....',
      '...w.....oLlko....',
      '...w.....oLlko....',
      '...w....oLlko.....',
      '...w....oLlko.....',
      '...w....oLlko.....',
      '...w...oLlko......',
      '...w...oLlko......',
      '...w..oLlko.......',
      '...w.oLko.........',
      '...woaao..........',
      '....oAao..........',
      '.....oo...........',
    ],
  },

  /** 장궁: 키만큼 긴 활. 사거리형 궁수용. */
  // 96×120 네이티브
  wpn_longbow: {
    w: 21, h: 75, ax: 15, ay: 36, scale: 3,
    px: [
      '.....oo..............',
      '....obao.............',
      '....oaao.............',
      '...woAao.............',
      '...w.oLko............',
      '...w.oLlko...........',
      '...w.oLlko...........',
      '...w..oLlko..........',
      '...w..oLlko..........',
      '...w..oLlko..........',
      '...w...oLlko.........',
      '...w...oLlko.........',
      '...w...oLlko.........',
      '...w....oLlko........',
      '...w....oLlko........',
      '...w....oLlko........',
      '...w.....oLlko.......',
      '...w.....oLlko.......',
      '...w.....oLlko.......',
      '...w......oLlko......',
      '...w......oLlko......',
      '...w......oLlko......',
      '...w.......oLlko.....',
      '...w.......oLlko.....',
      '...w.......oLlko.....',
      '...w........oLlko....',
      '...w........oLlko....',
      '...w........oLlko....',
      '...w.........oLlko...',
      '...w.........oLlko...',
      '...w..........oLlko..',
      '...w..........oLlkko.',
      '...w..........oLllkko',
      '...w..........oAaabbo',
      '...w..........oAaabbo',
      '...w..........oLllkko',
      '...w..........oLllkko',
      '...w..........odLllko',
      '...w..........oLllkko',
      '...w..........odLllko',
      '...w..........oLllkko',
      '...w..........odLllko',
      '...w..........oAaabbo',
      '...w..........oAaabbo',
      '...w..........oLllkko',
      '...w..........oLllko.',
      '...w..........oLlko..',
      '...w.........oLlko...',
      '...w.........oLlko...',
      '...w........oLlko....',
      '...w........oLlko....',
      '...w........oLlko....',
      '...w.......oLlko.....',
      '...w.......oLlko.....',
      '...w.......oLlko.....',
      '...w......oLlko......',
      '...w......oLlko......',
      '...w......oLlko......',
      '...w.....oLlko.......',
      '...w.....oLlko.......',
      '...w.....oLlko.......',
      '...w....oLlko........',
      '...w....oLlko........',
      '...w....oLlko........',
      '...w...oLlko.........',
      '...w...oLlko.........',
      '...w...oLlko.........',
      '...w..oLlko..........',
      '...w..oLlko..........',
      '...w..oLlko..........',
      '...w.oLlko...........',
      '...w.oLko............',
      '...woaao.............',
      '....oAao.............',
      '.....oo..............',
    ],
  },

  /** 석궁: 위로 향한 볼트 + 가로로 뻗은 활대 + 개머리. */
  // 96×120 네이티브
  wpn_crossbow: {
    w: 33, h: 48, ax: 16, ay: 36, scale: 3,
    px: [
      '................o................',
      '...............ono...............',
      '...............owo...............',
      '..............oMnwo..............',
      '.............oMmnnwo.............',
      '.............oMMmnno.............',
      '..............oMmno..............',
      '..............oMmno..............',
      '..............oLlko..............',
      '..............oLlko..............',
      '..............odLlo..............',
      '.wwwwwwwwwwwwwoLlkowwwwwwwwwwwww.',
      '.ooooooooooooooooooooooooooooooo.',
      'oAAaaaaaaaaabbbbbbbbbaaaaaaaaaAAo',
      'ommmnnnnnnnnnnnnnnnwwwnnnnnnnnnno',
      'oMMMMMMmmmmmAaaabbaaAmmmmmnnnnnno',
      '.ooooMMMMMMMAAaaaaaAAmmmmmmmoooo.',
      '.....ooooMMMAAaaaaaAAmmmoooo.....',
      '.........oooAAAaaaAAAooo.........',
      '............oMMdmmnno............',
      '............oMMdmmnno............',
      '............oMMdmmnno............',
      '............oMMdmmnno............',
      '............oAaaabbao............',
      '............oAAaaaaAo............',
      '............oMMdmmnno............',
      '............oMMdmmnno............',
      '.........oooMmmnnnmmMooo.........',
      '.........oMMmmnnnnmmMMMo.........',
      '.........oMAaaabbbaaaAMo.........',
      '.........oMMMmmmmmmmMMMo.........',
      '.........oooMMmmmmmMMooo.........',
      '............oLLllkkko............',
      '............oLLllkkko............',
      '............odLLllkko............',
      '............oLLllkkko............',
      '............oLLllkkko............',
      '............oLLllkkko............',
      '............odLLllkko............',
      '............oLLllkkko............',
      '............oLLllkkko............',
      '............oLLllkkko............',
      '............odLLllkko............',
      '............oLLllkkko............',
      '............oLLllkkko............',
      '...........oAaaabbbaAo...........',
      '...........oAAaaaaaAAo...........',
      '............ooooooooo............',
    ],
  },

  /** 마법 지팡이: 긴 나무대 끝에 마력 결정이 박혀 있다. */
  // 96×120 네이티브
  wpn_staff: {
    w: 19, h: 78, ax: 9, ay: 57, scale: 3,
    px: [
      '.......ooooo.......',
      '.....oogggggoo.....',
      '....ogggggfffgo....',
      '...oGggggfffffgo...',
      '...oGggggffffffo...',
      '..oGGggggfffffggo..',
      '..oGGgggggffffggo..',
      '..oGGGggggggggggo..',
      '..oGGGGgggggggggo..',
      '..oGGGGGggggggggo..',
      '...oGgggGGggggGo...',
      '...ogggggGGGGGGo...',
      '....oggggGGGGGo....',
      '.....oogGGGGoo.....',
      '.......oGGGo.......',
      '....ooodddddooo....',
      '....oMMmmmnnwno....',
      '....oAAaaaabbbo....',
      '....oAaaaaabbbo....',
      '.....oMmmmnnwo.....',
      '.....oMMmmnnwo.....',
      '......oMmmnno......',
      '......oLLllko......',
      '......oLlllko......',
      '......oLLlkko......',
      '......oLLllko......',
      '......oLLlllo......',
      '......oLLLlko......',
      '......oLLllko......',
      '......oLLllko......',
      '......oLlllko......',
      '......oLLlkko......',
      '......oLLllko......',
      '......oLLlllo......',
      '......oLLLlko......',
      '......oLLllko......',
      '......oLLllko......',
      '......oLlllko......',
      '......oLLlkko......',
      '......oLLllko......',
      '......oLLlllo......',
      '......oLLLlko......',
      '......oLLllko......',
      '......oLLllko......',
      '......oLlllko......',
      '.....oAAaaaabo.....',
      '.....oAaaaabbo.....',
      '.....oAAaaabbo.....',
      '.....oLLlllkko.....',
      '.....oLLllkkko.....',
      '.....oLLLllkko.....',
      '.....odLLLlldo.....',
      '.....oLLlllkko.....',
      '.....oLLllkkko.....',
      '.....oLLLllkko.....',
      '.....odLLLlldo.....',
      '.....oLLlllkko.....',
      '.....oLLllkkko.....',
      '.....oLLLllkko.....',
      '.....odLLLlldo.....',
      '.....oLLlllkko.....',
      '.....oLLllkkko.....',
      '.....oLLLllkko.....',
      '.....odLLLlldo.....',
      '.....oLLlllkko.....',
      '.....oLLllkkko.....',
      '.....oLLLllkko.....',
      '.....oAAaaaabo.....',
      '.....oAaaaabbo.....',
      '.....oAAaaabbo.....',
      '......oLLllko......',
      '......oLLllko......',
      '......oLlllko......',
      '......oLLlkko......',
      '......oMmmnno......',
      '.......omnwo.......',
      '........ono........',
      '.........o.........',
    ],
  },

  /** 완드: 짧은 지휘봉. 끝에 작은 마력 보석. */
  // 96×120 네이티브
  wpn_wand: {
    w: 13, h: 39, ax: 6, ay: 27, scale: 3,
    px: [
      '.....ooo.....',
      '....ogggo....',
      '...ogggggo...',
      '..oGgggfffo..',
      '.oGGggffffgo.',
      'oGGGgggfffggo',
      'oGGGggggggggo',
      '.oGGgggggggo.',
      '..ogggggggo..',
      '...oggGGGo...',
      '....oGGGo....',
      '.....oGo.....',
      '...oodddoo...',
      '...oAaabbo...',
      '...oMmnnwo...',
      '....oLlko....',
      '....oLlko....',
      '....oLllo....',
      '....oLlko....',
      '....oLlko....',
      '....oLLko....',
      '....oLlko....',
      '...oLLlkko...',
      '...oLllkko...',
      '...oLLllko...',
      '...odLLldo...',
      '...oLLlkko...',
      '...oLllkko...',
      '...oLLllko...',
      '...odLLldo...',
      '...oLLlkko...',
      '...oLllkko...',
      '...oLLllko...',
      '...oAaabbo...',
      '...oAaaabo...',
      '...oMmnnwo...',
      '....omnno....',
      '.....ono.....',
      '......o......',
    ],
  },

  /** 마도서: 손 위에 펼쳐 든 두꺼운 책. 중앙에 마력 문양. */
  // 96×120 네이티브
  wpn_tome: {
    w: 33, h: 24, ax: 15, ay: 21, scale: 3,
    px: [
      'ooooooooooooooooooooooooooooooooo',
      'oLkkkkkkkkkkkkkkkkkkkkkkkkkkkkkko',
      'oLLllllllllllllllkkkkkkkkkkkkkkko',
      'oLLlaAbbbbabbbbbabbbbbabbbbbbkkko',
      'oLLlAAaaaaaaaaaaaaaaaaaaaaabbkkko',
      'oLLlAAddddddddbbbbbddddddddbbkkko',
      'oLLlAAdLLLLLLbgggffbLLLLLLlbbkkko',
      'oLLlAAdLLLLLAGggfffgbLLLLLlbbkkko',
      'oLLLAAdaaaaAGGggfffggbbbbblbbkkko',
      'oLLLAAdAAALAGGGggggggbLaaalbblkko',
      'oLLLAAdLLLLLAGGGgggGbLLLLLlbbllko',
      'oLLLAAdLLLLLAAGGGGGAbLLLLLlbbllko',
      'oLLLAAdLLLLLLLAAAAALLLLLLLlbbllko',
      'oLLLAAaaaaaaaaaaaaaaaaaaaaabbllko',
      'oLLLAAAAAAAAAAAAAAAAAAAAAAAballko',
      'oLLLLLLLLLLLLLLLLLlllllllllllllko',
      'oLLAAaaaaaaaaaaaaaaaaaaaaaaabblko',
      'odddddddddddddddddddddddddddddddo',
      '.oCCCCCCCCCCCCCCCCCCCCCCCCCCCCCo.',
      '.ovvcvvvcvvvcvvvcvvvcvvvcvvvcvvo.',
      '.occccdcccdcccdcccdcccdcccdcccdo.',
      '.ovvvcvvvvcvvvvcvvvvcvvvvcvvvvco.',
      '..oCCCCdCCCCCdCCCCCdCCCCCdCCCCo..',
      '..ooooooooooooooooooooooooooooo..',
    ],
  },

  /** 클로: 주먹에 채우는 세 갈래 갈고리 발톱. */
  // 96×120 네이티브
  wpn_claw: {
    w: 19, h: 33, ax: 9, ay: 24, scale: 3,
    px: [
      '.....o.....o.....o.',
      '.....o.....o.....o.',
      '....ono...ono...ono',
      '....omo...omo...omo',
      '...ono...ono...ono.',
      '...omo...omo...omo.',
      '...ono...ono...ono.',
      '..oMmno.oMmno.oMmno',
      '.oMmwo.oMmwo.oMmwo.',
      '.oMmwo.oMmwo.oMmwo.',
      '.oMmwo.oMmwo.oMmwo.',
      '.oMmno.oMmno.oMmno.',
      '.odmno.odmno.odmno.',
      '.odmno.odmno.odmno.',
      '.odMMMommnnnownnmo.',
      '.oMMmmmmnnnnwnnmmo.',
      '.oMmmmmnnnnwnnnmmo.',
      '.oAAaaaaaabbbbbbbo.',
      '.oLlllllllkkkkkkko.',
      '.oLbllllllkkkkbkko.',
      '.odddddddddddddddo.',
      '.oLLLlllllkkkkkkko.',
      '..oLLllllkkkkkkko..',
      '...oooollkkkoooo...',
      '.......oLlko.......',
      '.......oLLko.......',
      '.......ollko.......',
      '.......oLlko.......',
      '.......oLLko.......',
      '.......ollko.......',
      '......oAaabbo......',
      '.......oaabo.......',
      '........ooo........',
    ],
  },

  /** 오브: 손 위에 떠 있는 마력 구슬 + 금속 받침. */
  // 96×120 네이티브
  wpn_orb: {
    w: 25, h: 30, ax: 12, ay: 24, scale: 3,
    px: [
      '.........ooooooo.........',
      '.......oogggggggoo.......',
      '......oGggggggggggo......',
      '.....oGggggggggffggo.....',
      '....oGGgggggggfffffgo....',
      '...oGGGggggggffffffggo...',
      '...oGGGggggggffffffggo...',
      '..oGGGGggggggffffffgggo..',
      '..oGGGGgggggggffffggggo..',
      '..oGGGGgggggggggggggggo..',
      '..oGGGGGggggggggggggggo..',
      '..oGGGGGggggggggggggggo..',
      '..oGGGGGGgggggggggggggo..',
      '..oGGGggGGGgggggggggggo..',
      '...oGggggGGGggggggggGo...',
      '...oggggggGGGGGGGGGGGo...',
      '....ogggggGGGGGGGGGGo....',
      '.....oabgGGGGGGGGbao.....',
      '......oAaaGGGGGbbbo......',
      '.......oAaaaaaabbo.......',
      '........oAaaaaabo........',
      '........oAaaaabbo........',
      '.........oAaaabo.........',
      '..........oAabo..........',
      '..........oabbo..........',
      '..........oAabo..........',
      '..........oabbo..........',
      '..........oaabo..........',
      '.........oAaabbo.........',
      '..........ooooo..........',
    ],
  },

  // ── 방패 / 보조장비 (앵커 = 손잡이 중심. spritegen 이 SHIELD_OFFSET 만큼 앞으로 민다) ──
  // 방패면이 "앞을 향해 있다"고 읽히도록 전부 같은 규칙으로 칠한다.
  //   뒤(x 작은 쪽) = 그림자 M/C  →  가운데 = 기본 m/c + 문양 a/A  →  앞(x 큰 쪽) = 하이라이트 w
  // 세로로는 머리(y14 위)를 절대 침범하지 않게 잡는다. 타워 실드도 목 아래에서 시작한다.
  /** 버클러: 주먹만 한 소형 원형 방패. 가운데 돌기(보스)에 앞쪽 반사광. */
  // 96×120 네이티브
  shd_buckler: {
    w: 28, h: 28, ax: 14, ay: 14, scale: 3,
    px: [
      '...........oooooo...........',
      '........ooommmmmmooo........',
      '......oommbbbbbbbbmmoo......',
      '.....ommbbbMMMMMMbbbmmo.....',
      '....oMaaMMmmmmnnnnMMbbmo....',
      '...oMaaMmmmmmmnnnnnnMbbmo...',
      '..oMaadmmmnnnnnnnnnnnMbbmo..',
      '..oMadmmmnmmmmmmnnwnnnMbmo..',
      '.oMadmmmnmmmmmmmmwwwnnnMbmo.',
      '.oMadmmdmmmmmmmmmwwwnnnMbmo.',
      '.oaammdmmmmAAAbAAmwnnnnnbbo.',
      'oMadmmdmmmAAbbbbAAmmnnnnMbmo',
      'oMadMmdmmmAaabbbbAmmmnmmMbmo',
      'oMadMMdmmmAaaabbbAmmmnmmMbmo',
      'oMAdMMdmmmdaaaaabAmmmnmmMbmo',
      'oMAdMMdMmmdAaaaaaAmmmnmmMbmo',
      'oMAdMMdMMmddAAaaAAmmmnmmMbmo',
      '.oAAMMdMMMmddddAAmmmmnmmbbo.',
      '.oMAdMMdMMMmmmmmmmmmnmmMamo.',
      '.oMAdMMMdMMMmmmmmmmdmmmMamo.',
      '..oMAdMMMdMMMMmmmmdmmmdaMo..',
      '..oMAAdMMMddddddddmmmdaaMo..',
      '...oMAAdMMMMMMMMMmmmdaaMo...',
      '....oMAAddMMMMMMMMddaaMo....',
      '.....oMMAAAddddddaaaMMo.....',
      '......ooMMAAAAAAaaMMoo......',
      '........oooMMMMMMooo........',
      '...........oooooo...........',
    ],
  },

  /** 라운드 실드: 금속 테 + 천을 씌운 방패면. 앞 테가 번쩍이고 가운데 십자 문양이 선다. */
  // 96×120 네이티브
  shd_round: {
    w: 34, h: 34, ax: 17, ay: 17, scale: 3,
    px: [
      '.............oooooooo.............',
      '..........ooommmmmmmmooo..........',
      '........oommmbbbbbbbbmmmoo........',
      '.......ommbbbbCCCCCCbbbbmmo.......',
      '......ommabCCcccbbvvvCCbbmmo......',
      '.....oMaaCCcccccbbvvvvvCCbbmo.....',
      '....oMaaCcccccccbbvvvvvvvCbbmo....',
      '...oMaaCccccccccbbvvvvvvvvCbbmo...',
      '..oMMadcCcccccccbbvvvvvvvCvCbmmo..',
      '..oMadccCcccccccbbvvvvvvvCvcCbmo..',
      '.oMaadccCcccccccabvvvvvvvCvcCbbmo.',
      '.oMadCccCcccccccaavvvvvvvCvccCbmo.',
      '.oMadCCcCcccccAAAAAAvvcvvCvccCbmo.',
      'oMaaCCCcCccccAAmnnnAAvcccCvcccbbmo',
      'oMadCCCcCcccddmmmnwnAAcccCvcccCbmo',
      'oMadCCCcCcccdmmmmwwnnAcccCvcccCbmo',
      'oMAdaaaaaaaadmmmmmmmnAaabbbbbbCbmo',
      'oMAdAaaaaaaadMmmmmmmmAaaabbbbbCbmo',
      'oMAdCCCcCcccdMMMmmmmmAcccCvcccCbmo',
      'oMAdCCCcCcccddMMMmmmAAcccCvcccCbmo',
      'oMAACCCCCcccCddMMMmddccccCvcccbbmo',
      '.oMAdCCCCcccCCddddddcccccCvccCbmo.',
      '.oMAdCCCCcccCCCcaacccccccCvccCbmo.',
      '.oMAAdCCCcCcCCCCaacccccccCccCaamo.',
      '..oMAdCCCcCCCCCCaacccccccCccCamo..',
      '..oMMAdCCcCCCCCCaacccccccCcdaMMo..',
      '...oMAAdCCCCCCCCaaccccccccdaaMo...',
      '....oMAAdCCCCCCCaacccccccdaaMo....',
      '.....oMAAddCCCCCAacccccddaaMo.....',
      '......oMMAAddCCCAACccddaaMMo......',
      '.......oMMAAAAddddddaaaaMMo.......',
      '........ooMMMAAAAAAAAMMMoo........',
      '..........oooMMMMMMMMooo..........',
      '.............oooooooo.............',
    ],
  },

  /** 카이트 실드: 위는 둥글고 아래로 뾰족한 기병용 방패. 앞모서리 한 줄이 하얗게 선다. */
  // 96×120 네이티브
  shd_kite: {
    w: 28, h: 41, ax: 14, ay: 20, scale: 3,
    px: [
      '......oooooooooooooooo......',
      '....ooMMMMMMmmmmmnnnnnoo....',
      '...oMMAAAaaaaabbbbbbbbnno...',
      '..oMAAdddddddddCCCCCCCbbno..',
      '.oMAAdCCCCcccccvvvvvvvCbbno.',
      '.oMAdCCCCdcccaavvvCvvvvCbno.',
      'oMMAdCCCCdcccaavvvCvvvvCbnno',
      'oMMACCCCCdcccaavvvCvvvvvbnno',
      'oMMACCCCCdcccaavvvCvvvvvbnno',
      'oMMACCCCCdcccaavvvCvvvvvbnno',
      'oMMACCCCCdccaaaavvCvvvvvbnno',
      'oMMACCCCCdcaadCabvCvvvvvbnno',
      'oMMACCCCCdaaddCCbbCvvvvvbnno',
      'oMMACCCCCdaadnnCbbCvvvvvbnno',
      'oMMACCCCCAadmmwnCbbvvvvvbnno',
      'oMMACCCCAAddmmwwCCbbvvvvbnno',
      'oMMACCCAAddMmmwmnCCbbvvvbnno',
      'oMMAdCCCAAddMmmmCCbbvvvCbnno',
      '.oMAdCCCCAadMMmmCbbvvvvCbno.',
      '.oMAdCCCCdaadMMCbbCvvvvCbno.',
      '.oMAdCCCCdaaddCCbbCvvvvCbno.',
      '.oMMAdCCCdcaadCabvCvvvCbnno.',
      '..oMAdCCCdccaaaavvCvvvCbno..',
      '..oMAdCCCdcccaavvvCvvvCbno..',
      '...oMAdCCdcccaavvvCvvCbno...',
      '...oMAdCCdcccaavvvCvvCbno...',
      '...oMMAdCdcccaavvvCvCbnno...',
      '....oMAdCdcccaavvvCvCbno....',
      '....oMMAddcccaavvvCCbnno....',
      '.....oMAdCCccaavvvvCbno.....',
      '......oMAdCccaavvvCbno......',
      '......oMAACCcaavvvbbno......',
      '.......oMAdCcaavvCbno.......',
      '........oMAdcaavCbno........',
      '........oMAAcaavbbno........',
      '.........oMAdaaCbno.........',
      '..........oMadCbno..........',
      '..........oMMabnno..........',
      '...........oMabno...........',
      '............ommo............',
      '.............oo.............',
    ],
  },

  /** 타워 실드: 몸 절반을 가리는 대형 장방형 방패. 위 모서리를 한 칸 내려
   *  어떤 포즈에서도 턱·머리를 가리지 않는다. 문양 두 단이 앞을 향해 보인다. */
  // 96×120 네이티브
  shd_tower: {
    w: 32, h: 62, ax: 16, ay: 26, scale: 3,
    px: [
      '..oooooooooooooooooooooooooooo..',
      '.oaAAaaaadnaaabbdnbbbbbdnbbbbbo.',
      '.oadddddddnddddddnMMMMMdnMMMMbo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oddddddddddddddddddddddddddddo.',
      '.oaAAaaaaAAaabAbbabbbbbbbbbbbbo.',
      '.oaAdaaaadAaabdbbabdbbbbdbbbbbo.',
      '.oddddddddddddddddddddddddddddo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oadMMmmmdnmmAAAAAAnnnndnnnnMbo.',
      '.oadMMmmmdnmAbbbbbbAnnndnnnnMbo.',
      '.oadMMmmmdndaamnnnbbAnndnnnnMbo.',
      '.oadMMmmmddaammmnwnbbAndnnnnMbo.',
      '.oadMMmmmddammmmwwnnbAndnnnnMbo.',
      '.oadMMmmmddaMmmmmwnnbAndnnnnMbo.',
      '.oadMMmmmddAMMmmmmmnbAndnnnnMbo.',
      '.oadMMmmmddAMMMmmmmmbAndnnnnMbo.',
      '.oadMMmmmddAAMMMmmmaaAndnnnnMbo.',
      '.oadMMmmmdndAAMMMmaaAnndnnnnMbo.',
      '.oadMMmmmdnmdAAAAaadnnndnnnnMbo.',
      '.oadMMmmmdnmmddddddnnnndnnnnMbo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oddddddddddddddddddddddddddddo.',
      '.oaAAaaaaaAaabbbbabbbbbbbbbbbbo.',
      '.oaAAaaaaAAaabAbbabbbbbbbbbbbbo.',
      '.oaAdaaaadAaabdbbabdbbbbdbbbbbo.',
      '.oddddddddddddddddddddddddddddo.',
      '.oadMMmmmdnmmAAAAAAnnnndnnnnMbo.',
      '.oadMMmmmdnmAbbbbbbAnnndnnnnMbo.',
      '.oadMMmmmdndaamnnnbbAnndnnnnMbo.',
      '.oadMMmmmddaammmnwnbbAndnnnnMbo.',
      '.oadMMmmmddammmmwwnnbAndnnnnMbo.',
      '.oadMMmmmddaMmmmmwnnbAndnnnnMbo.',
      '.oadMMmmmddAMMmmmmmnbAndnnnnMbo.',
      '.oadMMmmmddAMMMmmmmmbAndnnnnMbo.',
      '.oadMMmmmddAAMMMmmmaaAndnnnnMbo.',
      '.oadMMmmmdndAAMMMmaaAnndnnnnMbo.',
      '.oadMMmmmdnmdAAAAaadnnndnnnnMbo.',
      '.oadMMmmmdnmmddddddnnnndnnnnMbo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oddddddddddddddddddddddddddddo.',
      '.oaAAaaaaAAaabAbbabbbbbbbbbbbbo.',
      '.oaAdaaaadAaabdbbabdbbbbdbbbbbo.',
      '.oddddddddddddddddddddddddddddo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oadMMmmmdnmmmnndnmnnnndnnnnMbo.',
      '.oMAdMmmmdnmmmnndnmnnnndnnnMbmo.',
      '..oAdMmmmdnmmmnndnmnnnndnnnMbo..',
      '..oMAdMmmdnMmmnndnmnnnndnnMbmo..',
      '...oAdMmmdnMmmnndnmnnnndnnMbo...',
      '....oaddmdnMmmnndnmnnnndnMbo....',
      '.....oaaddnMmmnndnmnnnMdbbo.....',
      '......ooadnddddddnMMMMbboo......',
      '........ooAAaabbdnbbbboo........',
      '..........oooooooooooo..........',
    ],
  },

  /** 보조 오브: 왼손에 띄우는 마력 구체. 빛은 앞·위에서 든다. */
  // 96×120 네이티브
  shd_orb: {
    w: 28, h: 28, ax: 14, ay: 14, scale: 3,
    px: [
      '...........oooooo...........',
      '........oooggggggooo........',
      '......ooGGGGggggggggoo......',
      '.....oGGGgggggfgggggggo.....',
      '....oGGGgggggggffffggggo....',
      '...oGGggggggggggffffggggo...',
      '..oGGgggggfgggggggfffggggo..',
      '..oGGgggggggggggggfgffgggo..',
      '.oGGgggggggggggggggggffgggo.',
      '.oGGgggggggggggggggggfffggo.',
      '.oGGggggggggfffffgggggffggo.',
      'oGgGgggggggfffffffgggggfgggo',
      'oGggggggggffffffffgggggggggo',
      'oGggGgggggffffffffgggggggggo',
      'oGggGgggggffffffffgggggggGgo',
      'oGggGggggggfffffffgggggggGGo',
      'oGggGGgggggffffffggggggggGGo',
      '.oGggGgfGggggfffgggggggggGo.',
      '.oGggGGgggggggggggggfggggGo.',
      '.oGgggGGgGggggggggggggggGGo.',
      '..oGgggGGgGggggggggggggGGo..',
      '..oGGgggGGgGgggggggggggGGo..',
      '...oGGgggGGGggggggggggGGo...',
      '....oGGggggGGGGGGGGGGGGo....',
      '.....oGGgggggggggggGGGo.....',
      '......ooGGGggggggGGGoo......',
      '........oooGGGGGGooo........',
      '...........oooooo...........',
    ],
  },

  /** 횃불: 불꽃이 타오르는 보조 손 장비. */
  // 96×120 네이티브
  shd_torch: {
    w: 22, h: 44, ax: 10, ay: 28, scale: 3,
    px: [
      '.........GGgG.........',
      '.......GGGGggGG.......',
      '......GGGGgggGGG......',
      '.....GGGGGgggggGG.....',
      '....GGGGGgggggggGG....',
      '....GGGGgffffggggG....',
      '....GGGggfffffgggG....',
      '....GGGggffffffggG....',
      '....GGgggffffffggG....',
      '....GGGgfffffffggG....',
      '.....GGgfffffffgG.....',
      '......GgfffffffG......',
      '......GGgffffffG......',
      '.......GGfffffG.......',
      '........GffffG........',
      '........GGfffG........',
      '........GGfffG........',
      '.....oooddddAAooo.....',
      '......oAaabbbbbo......',
      '......oAaabbbbbo......',
      '.......oMmmnnno.......',
      '.......oMmmnnwo.......',
      '........ommnno........',
      '.......oAaaabbo.......',
      '.......oAaaabbo.......',
      '........oLlkko........',
      '........ollkko........',
      '........ollkko........',
      '........oddLLo........',
      '........oLlkko........',
      '........ollkko........',
      '.......oAaaabbo.......',
      '........oddLLo........',
      '........oLlkko........',
      '........ollkko........',
      '........ollkko........',
      '........oddLLo........',
      '........oLlkko........',
      '........ollkko........',
      '........ollkko........',
      '........oddLLo........',
      '.......oAaaaabo.......',
      '........oAaaao........',
      '........oooooo........',
    ],
  },

  /** 패링 대거: 왼손에 드는 방어용 단검. */
  // 96×120 네이티브
  shd_dagger: {
    w: 16, h: 38, ax: 7, ay: 29, scale: 3,
    px: [
      '.......oo.......',
      '......onno......',
      '......onwo......',
      '......onno......',
      '......onno......',
      '.....onnnno.....',
      '.....oMnnno.....',
      '.....oMnwno.....',
      '.....omnwmo.....',
      '.....omnnmo.....',
      '.....omnnmo.....',
      '.....omnnmo.....',
      '....oMmnnmno....',
      '....oMmnnmno....',
      '....oMmnnmno....',
      '....oMmnwmno....',
      '....oMmnnmno....',
      '....oMmnnmno....',
      '....oMmnnmno....',
      '....oMmnnmno....',
      '...oMMmnnmnno...',
      '..oAAaaaaabbbo..',
      '.oAAAAaaaaaabbo.',
      '..ooAAAaaaaaoo..',
      '....oAddaaao....',
      '.....oLlkko.....',
      '.....oLlkko.....',
      '.....oddLLo.....',
      '.....oLlkko.....',
      '.....oLlkko.....',
      '.....oddLLo.....',
      '.....oLlkko.....',
      '.....oLlkko.....',
      '.....oddLLo.....',
      '.....oLlkko.....',
      '....oaaaaabo....',
      '....oAaaaaao....',
      '.....oooooo.....',
    ],
  },
};
