// 클래스별 태그 — 워크플로 class-illust-prompts-v2 (2026-09-06, 노출 규칙 포함) 가 썼다. 손으로 고쳐도 되지만 규칙(illustprompts.mjs 머리말)을 지켜라.
// 머리색·눈색·배경·성별 단어 없음 (표식·공통 접미가 정한다). { id: { name, style, tier, tags, hairStyle, pose } }
export const CLASS_TAGS = {
  swordsman: { name: "검사", style: "fighter", tier: 1, equip: ["sword","shield"],
    tags: "worn red military jacket, open jacket, tarnished gold buttons, simple gold epaulettes, white bandeau, bare midriff, short red pleated skirt, bare thighs, scuffed knee-high brown leather boots, plain longsword held in one hand, small round shield strapped to back, leather gloves, confident smirk",
    hairStyle: "short bob", pose: "longsword held point-down at side, shield on back" },
  spearman: { name: "창병", style: "lancer", tier: 1, equip: ["spear","shield"],
    tags: "spear warrior, worn steel breastplate over cropped sleeveless dark blue tunic, bare shoulders, bare midriff, short dark blue pleated skirt, bare thighs, plain iron spear held upright, small round wooden shield on back, leather belt, brown leather boots, scuffed armor, bareheaded",
    hairStyle: "short bob", pose: "standing, spear held upright, shield on back" },
  shieldman: { name: "방패병", style: "tank", tier: 1, equip: ["mace","sword","shield"],
    tags: "flanged mace, scuffed steel tower shield, dented steel breastplate cropped above bare midriff, sleeveless, bare shoulders, single scratched steel pauldron, worn brown leather miniskirt, bare thighs, scuffed knee-high greaves, battered open-faced steel helm, longsword at hip, partial plate armor, simple worn gear, stalwart",
    hairStyle: "messy short hair", pose: "tower shield planted in front, mace resting at side" },
  archer: { name: "궁수", style: "archer", tier: 1, equip: ["bow","dagger"],
    tags: "ranger archer, worn brown hooded cloak, hood down, sleeveless cropped brown leather vest, bare midriff, bare shoulders, short leather shorts, bare thighs, leather thigh strap, plain wooden longbow in hand, quiver of arrows on back, small dagger at hip, worn boots",
    hairStyle: "low braid over shoulder", pose: "standing, longbow held at side, relaxed stance" },
  rogue: { name: "도적", style: "rogue", tier: 1, equip: ["dagger","sword"],
    tags: "assassin rogue, worn dark hooded cloak, hood down, black half face mask, cropped brown leather vest worn open over black bandeau, short black leather shorts, bare thighs, thigh strap, fingerless gloves, patched knee boots, dagger in reverse grip, longsword sheathed at hip, lean, sly",
    hairStyle: "messy short hair", pose: "dagger held low in reverse grip" },
  apprentice: { name: "견습마법사", style: "mage", tier: 1, equip: ["staff","wand"],
    tags: "mage, oversized wide-brimmed wizard hat, worn patched off-shoulder dark blue short robe dress with faded gold trim, bare shoulders, bare thighs, dark blue thigh-high cloth socks, brown leather belt, plain wooden staff with small dim gold crystal, short wand tucked in belt",
    hairStyle: "short bob", pose: "standing, clutching wooden staff upright with both hands close to chest, slightly nervous" },
  acolyte: { name: "수도사", style: "healer", tier: 1, equip: ["mace","staff"],
    tags: "acolyte, worn white off-shoulder pilgrim robe top, bare shoulders, short white side-slit wrap skirt, bare thighs, brown rope belt, wooden prayer beads, bandaged hands, iron flanged mace, wooden staff on back, gold sun pendant, gentle, prayer, soft golden glow on palm",
    hairStyle: "short bob", pose: "flanged mace held low at side, other hand raised palm out in blessing" },
  berserker: { name: "광전사", style: "fighter", tier: 2, equip: ["greatsword","axe"],
    tags: "sleeveless red military vest worn open, gold epaulettes, crimson leather bikini armor top, bare muscular arms, bare midriff, red war paint, ripped black shorts, leather thigh straps, bare thighs, brown leather boots, zweihander greatsword resting on shoulder, battle axe at hip, feral grin",
    hairStyle: "messy short hair", pose: "greatsword resting on shoulder" },
  swordmaster: { name: "검성", style: "fighter", tier: 2, equip: ["katana","sword"],
    tags: "fitted red military jacket, high collar, gold epaulettes, gold buttons, deep cleavage cutout, gold crescent moon emblem, white sash, white gloves, black high-slit long skirt, bare thigh, thigh-high brown leather boots, katana held upright in one hand, longsword sheathed at hip, calm focused expression",
    hairStyle: "high ponytail", pose: "katana held upright at side" },
  dragoon: { name: "창기병", style: "lancer", tier: 2, equip: ["spear","shield"],
    tags: "spear warrior, polished steel breastplate with cleavage cutout over dark blue tunic, small steel spaulders, dark blue shorts, thigh-high brown riding boots, bare thighs above boots, cavalry spear held upright, round steel shield on back, open-faced steel helmet with red plume, red sash",
    hairStyle: "high ponytail", pose: "standing, spear held upright, one hand on hip" },
  halberdier: { name: "미늘창병", style: "lancer", tier: 2, equip: ["spear","scythe"],
    tags: "spear warrior, steel breastplate over dark blue bandeau top, bare midriff, chainmail shoulder mantle, brass-studded leather skirt with side cutouts, leather thigh straps, bare thighs, heavy spear with hooked blade held upright, short scythe hung at hip, dark blue headband, thick leather gloves",
    hairStyle: "twin braids", pose: "standing, spear planted upright, gripped with both hands" },
  knight: { name: "중갑기사", style: "tank", tier: 2, equip: ["sword","mace","shield"],
    tags: "longsword, polished steel breastplate with cleavage cutout, layered steel pauldrons, steel gauntlets, short white split surcoat with faded heraldic crest, bare thighs, thigh-high steel greaves with bare thigh gap, steel kite shield, flanged mace at hip, crimson-plumed open-faced bascinet, partial plate armor, stalwart",
    hairStyle: "long straight hair", pose: "longsword held upright, kite shield at side" },
  guardian: { name: "수호기사", style: "tank", tier: 2, equip: ["mace","shield"],
    tags: "flanged mace, oversized steel tower shield with gold-trimmed rim, gold star emblem on shield, steel bikini-armor top, thick steel gorget, broad rounded pauldrons, bare midriff, steel hip tassets over navy shorts, full steel greaves, brown leather belt, partial plate armor, protective stance, stalwart",
    hairStyle: "short bob", pose: "tower shield raised in front, mace lowered at side" },
  sniper: { name: "저격수", style: "archer", tier: 2, equip: ["bow","crossbow"],
    tags: "ranger archer, long dark brown hooded coat worn open, hood down, dark leather bandeau top, cleavage, dark leather shorts, thigh-high leather boots, bare thigh gap, crimson armband, sleek longbow held ready, quiver of arrows at hip, compact crossbow slung on back",
    hairStyle: "short bob", pose: "standing, longbow drawn halfway, aiming" },
  hunter: { name: "사냥꾼", style: "archer", tier: 2, equip: ["crossbow","bow","dagger"],
    tags: "ranger archer, brown hooded cloak, hood down, fur mantle on bare shoulders, fur-trimmed bikini-style armor top, cleavage, short fur-trimmed loincloth skirt, bare thighs, heavy crossbow in both hands, longbow on back, quiver of arrows, dagger at belt, animal tooth necklace",
    hairStyle: "twin braids", pose: "standing, crossbow held across chest with both hands" },
  assassin: { name: "암살자", style: "rogue", tier: 2, equip: ["dagger","claw"],
    tags: "assassin rogue, sleek black leotard, deep cleavage cutout, short dark hooded mantle, hood down, black half face mask, clawed gauntlet on off hand, dagger held ready, crimson sash at waist, thigh-high black boots, bare thigh gap, lean, silent poised stance, sly",
    hairStyle: "long straight hair", pose: "dagger raised beside face, claw hand lowered" },
  outlaw: { name: "무법자", style: "rogue", tier: 2, equip: ["axe","dagger"],
    tags: "assassin rogue, dark wide-brim hat, black bandana face mask, tan leather duster coat worn open, black leather halter top, cleavage, bare midriff, bronze belt buckle, bandolier, dark fitted pants, rolled sleeves, battle axe held in one hand, dagger at hip, lean, sly, bounty hunter",
    hairStyle: "high ponytail", pose: "battle axe resting on shoulder, hand on hip" },
  elementalist: { name: "원소술사", style: "mage", tier: 2, equip: ["staff","wand","tome"],
    tags: "mage, wide-brimmed wizard hat with orange ribbon, cropped dark blue robe jacket open over orange bandeau, bare midriff, high-slit dark blue skirt with gold trim, bare thigh, scorched leather gloves, wooden staff with orange glowing crystal, orange flame wisps, spellbook chained at hip",
    hairStyle: "high ponytail", pose: "standing, staff planted at side in one hand, other hand raised with a small orange flame on the palm" },
  necromancer: { name: "강령술사", style: "necro", tier: 2, equip: ["wand","tome","scythe"],
    tags: "necromancer, off-shoulder black tattered short robe dress, side cutouts, bare thighs, leather thigh strap, crimson sash, pale skin, bone wand with small skull tip, grimoire chained at hip, bone scythe slung on back, dark aura",
    hairStyle: "wavy shoulder-length hair", pose: "standing, bone wand held forward, other hand resting on the chained grimoire at hip" },
  priest: { name: "사제", style: "healer", tier: 2, equip: ["staff","mace","tome"],
    tags: "cleric, gold-trimmed white cassock dress, keyhole cleavage cutout, sheer white sleeves, high-slit skirt, bare thigh, gold thigh strap, gold sun-embroidered stole, gold circlet, silver coin pouch, gold-ringed wooden staff, flanged mace at hip, leather grimoire, gentle smile, prayer, faint golden light",
    hairStyle: "low braid over shoulder", pose: "staff held upright in one hand, grimoire open in the other" },
  monk: { name: "수도승", style: "monk", tier: 2, equip: ["claw","mace"],
    tags: "martial artist monk, cropped sleeveless orange gi open over white chest wraps, cleavage, bare midriff, black sash, black shorts, bare thighs, shin wraps, iron clawed gauntlets, wooden prayer beads, headband, flanged mace at hip, golden glow on palm, muscular, fighting stance",
    hairStyle: "high ponytail", pose: "fists raised in guard stance" },
  madgeneral: { name: "광기의 대장군", style: "fighter", tier: 3, equip: ["axe","greatsword"],
    tags: "red military greatcoat draped over bare shoulders, gold epaulettes, gold medals, black leather corset, deep cleavage, bare midriff, black officer shorts, thigh-high brown leather boots, black peaked officer cap, ornate gold-inlaid battle axe held two-handed, greatsword on back, manic grin, scar across face",
    hairStyle: "long wavy hair", pose: "battle axe held across body two-handed" },
  bloodfiend: { name: "혈귀검사", style: "fiend", tier: 3, equip: ["katana","claw"],
    tags: "vampire, pale skin, fangs, open knee-length black long coat with crimson lining, black leather bandeau top, bare midriff, black shorts, bare thighs, knee-high boots, crimson sash, single clawed gauntlet, ornate katana with crimson-glowing blade, crimson blood-drop emblem, red glow",
    hairStyle: "high ponytail", pose: "standing, katana held low at side in right hand" },
  swordgod: { name: "검신", style: "fighter", tier: 3, equip: ["katana","sword"],
    tags: "long sleeveless red military coat worn open, gold epaulettes, white trim, white leotard with gold trim, cleavage, bare legs, white sash, gold sword emblem, brown leather boots, ornate katana with gold tsuba held two-handed, longsword sheathed on back, serene expression, golden glow along blade",
    hairStyle: "hime cut", pose: "katana held two-handed at ready" },
  skysplitter: { name: "파천검호", style: "fighter", tier: 3, equip: ["greatsword","katana"],
    tags: "cropped red military jacket, gold epaulettes, single steel pauldron, torn red half-cape, black strapless bandeau, bare midriff, gold lightning-crack emblem, asymmetric red skirt, leather thigh strap, bare thigh, brown leather boots, oversized greatsword planted point-down, katana sheathed at hip, white light cracks on blade",
    hairStyle: "low braid over shoulder", pose: "greatsword planted point-down, one hand on katana hilt" },
  dragoonlord: { name: "용기병 대장", style: "lancer", tier: 3, equip: ["spear","shield"],
    tags: "spear warrior, gold-trimmed steel breastplate over sleeveless dark blue tunic, bare arms, gold pauldrons, steel gauntlets, high-slit dark blue skirt, bare thigh, decorated gold-tipped spear held upright with crimson war banner, round shield with gold dragon emblem on back, dark blue cape",
    hairStyle: "long straight hair", pose: "standing, banner spear held upright, shield on back" },
  skylancer: { name: "천공창기사", style: "lancer", tier: 3, equip: ["spear","wand"],
    tags: "spear warrior, silver-steel breastplate over dark blue leotard, bare shoulders, bare thighs, silver knee greaves, single winged pauldron, slender spear crackling with white lightning held upright, wand tucked in belt, long white scarf, feather emblem on chest, silver circlet",
    hairStyle: "side ponytail", pose: "standing, spear held upright, crackling with lightning" },
  gatewarden: { name: "관문수호자", style: "tank", tier: 3, equip: ["spear","shield"],
    tags: "gold-banded steel spear, rectangular pavise shield with engraved portcullis emblem, fluted steel breastplate with side cutouts, bare waist, steel pauldrons, navy cape, high-slit navy armored skirt, bare thigh, leather thigh straps, steel sabatons, open-faced steel sallet helm, gold chest chain, partial plate armor, stalwart",
    hairStyle: "wavy shoulder-length hair", pose: "spear planted upright, pavise shield braced forward" },
  reaper: { name: "사신낫병", style: "lancer", tier: 3, equip: ["scythe","spear"],
    tags: "scythe warrior, blackened steel bikini armor top, bare midriff, tattered dark blue high-slit skirt, bare thighs, tattered black hooded cloak, hood down, large black-bladed scythe held upright, spear strapped on back, skull clasp on cloak, black shadow wisps around blade",
    hairStyle: "wavy shoulder-length hair", pose: "standing, scythe held upright, spear on back" },
  paladin: { name: "성전기사", style: "tank", tier: 3, equip: ["mace","sword","shield"],
    tags: "gold-inlaid flanged mace, ornate steel heater shield with golden cross emblem, off-shoulder short white dress with gold trim, bare shoulders, engraved gold breastplate, small gold pauldrons, bare thighs, gold-trimmed white thigh-high boots, longsword at hip, white cape, gold circlet, partial plate armor, stalwart",
    hairStyle: "high ponytail", pose: "mace raised slightly, heater shield held at chest" },
  blackknight: { name: "흑기사", style: "fighter", tier: 3, equip: ["greatsword","sword"],
    tags: "cropped red military jacket worn open over black plate bikini armor, gold epaulettes, black pauldrons, bare midriff, black tasset half-skirt, side slits, bare thighs, black knee-high greaves, crimson-lined tattered black cape, greatsword held point-down, both hands on pommel, longsword at hip, crimson aura wisps",
    hairStyle: "long straight hair", pose: "greatsword point-down, both hands on pommel" },
  bulwark: { name: "불굴의 성벽", style: "tank", tier: 3, equip: ["mace","shield"],
    tags: "heavy flanged mace, crimson tassel, massive crenellated tower shield with brick-pattern engraving, grey steel armored leotard with plunging cleavage cutout, oversized slab pauldrons, iron chains on shield arm, battlement emblem on chest, bare thighs, steel sabatons, open-faced heavy steel helm, partial plate armor, stalwart",
    hairStyle: "low braid over shoulder", pose: "tower shield planted squarely in front, mace resting on shoulder" },
  oathshield: { name: "서약의 방패", style: "oath", tier: 3, equip: ["mace","shield","tome"],
    tags: "holy paladin, white bikini armor top, gold cross emblem, bare midriff, gold pauldrons, gauntlets, short white pleated skirt, bare thighs, white thigh-high armored boots, short white cape, gold circlet, ornate flanged mace, gold cross kite shield, spellbook at hip, golden light barrier, serene",
    hairStyle: "long straight hair", pose: "standing, kite shield raised in front, flanged mace held upright" },
  masterarcher: { name: "신궁", style: "archer", tier: 3, equip: ["bow","crossbow"],
    tags: "ranger archer, brown and gold leather breastplate, cleavage cutout, bare arms, single gold pauldron, brown hooded cape, gold arrow emblem, hood down, gold circlet, long brown high-slit skirt, bare thigh, ornate gold-trimmed longbow, quiver of arrows, crossbow on back, tall boots",
    hairStyle: "long straight hair", pose: "standing, longbow held upright, free hand on hip" },
  shadowarcher: { name: "그림자 사수", style: "rogue", tier: 3, equip: ["crossbow","dagger"],
    tags: "assassin rogue, long dark hooded cloak, hood down, black half face mask, dark blue leather corset top, bare shoulders, short dark blue skirt, bare thighs, dagger at thigh, silver arrow emblem, ornate crossbow held across body, bolt quiver on back, black shadow wisps, lean, sly",
    hairStyle: "low braid over shoulder", pose: "crossbow held across chest" },
  beastlord: { name: "야수군주", style: "monk", tier: 3, equip: ["claw","axe"],
    tags: "martial artist monk, sleeveless crimson halter gi top, cleavage, bare midriff, brown wolf pelt mantle, fur-trimmed short skirt, bare thighs, thigh strap, bone clawed gauntlets, fang necklace, prayer beads, battle axe on back, muscular, fighting stance, feral grin, fangs",
    hairStyle: "long wild hair with braided sidelocks", pose: "one clawed hand extended forward, wide stance" },
  spiritranger: { name: "정령궁수", style: "archer", tier: 3, equip: ["bow","staff"],
    tags: "ranger archer, white feather-trimmed brown hooded cloak, hood down, backless halter top, bare shoulders, gold rune tattoos on bare arms, short feather-trimmed skirt, bare thighs, carved longbow with glowing gold runes, quiver of arrows, antler staff on back, white spirit wisps",
    hairStyle: "wavy shoulder-length hair", pose: "standing, longbow held loosely at side, free hand raised with glowing wisps" },
  shadowblade: { name: "그림자 밀사", style: "rogue", tier: 3, equip: ["dagger","claw","katana"],
    tags: "assassin rogue, black shinobi outfit, sleeveless top with side cutouts, short black slit skirt, bare thighs, dark cowl hood down, black half face mask, crimson-corded short mantle, clawed gauntlet on off hand, crimson-hilted dagger held ready, katana sheathed on back, black shadow tendrils, lean, sly",
    hairStyle: "short bob", pose: "dagger held forward, claw hand raised" },
  venomfang: { name: "독아", style: "rogue", tier: 3, equip: ["dagger","claw"],
    tags: "assassin rogue, black scaled bikini armor top, bare midriff, bare arms, crimson serpent emblem on chest, black scaled pauldron, dark hood down, fanged black half mask, black leather pants, crimson stitching, clawed gauntlet on off hand, dagger dripping black venom, black mist, lean, sly",
    hairStyle: "twin braids", pose: "dagger held out, black venom dripping from blade" },
  banditking: { name: "도적왕", style: "rogue", tier: 3, equip: ["axe","sword"],
    tags: "assassin rogue, fur-trimmed dark hooded coat draped over shoulders, hood down, black leather strapless top, deep cleavage, bare shoulders, gold circlet, gold coin necklace, black half mask at neck, scarred cheek, dark leather pants, brass-bound battle axe held upright, longsword at hip, lean, sly smirk",
    hairStyle: "wavy shoulder-length hair", pose: "battle axe planted, other hand on hip" },
  bladedancer: { name: "칼날무희", style: "fighter", tier: 3, equip: ["dagger","katana"],
    tags: "off-shoulder cropped red bolero jacket with gold epaulettes and gold fringe, bare shoulders, white bandeau, bare midriff, flowing red double-slit skirt, bare thighs, gold coin belt, gold bangles, brown leather dancer boots, ornate dagger held reversed, katana held low in other hand, playful smile",
    hairStyle: "side ponytail", pose: "dagger held reversed, katana held low in other hand" },
  archmage: { name: "대마법사", style: "mage", tier: 3, equip: ["staff","tome","wand"],
    tags: "mage, pointed wizard hat with gold star emblem, backless floor-length dark blue robe dress with gold embroidery, plunging cleavage cutout, sheer sleeves, short dark blue cape, ornate gold-capped wooden staff with large gold glowing crystal, orange ember particles, spellbook at hip",
    hairStyle: "long wavy hair", pose: "standing, ornate staff held upright beside body, other hand on hip, confident" },
  stormcaller: { name: "폭풍술사", style: "mage", tier: 3, equip: ["wand","staff"],
    tags: "mage, gold circlet with lightning bolt emblem, sleeveless high-collar dark blue robe top with gold trim, side cutouts, dark blue shorts, bare thighs, thigh-high black boots, dark blue half-cape, wand with white glowing crystal, crackling white-gold lightning, wooden staff on back",
    hairStyle: "long twin tails", pose: "standing, wand raised diagonally forward with lightning crackling at its tip, weight on one leg" },
  lichlord: { name: "사령왕", style: "necro", tier: 3, equip: ["staff","tome","scythe"],
    tags: "lich, necromancer, gold-trimmed floor-length black tattered robe, plunging cleavage cutout, sheer black sleeves, high side slit, black cape with crimson lining, bone crown, skull-topped bone staff with crimson gem, grimoire chained at waist, bone scythe on back, pale skin, dark aura",
    hairStyle: "long straight hair", pose: "standing, staff held upright at side, chin raised" },
  plaguelord: { name: "역병군주", style: "necro", tier: 3, equip: ["scythe","tome"],
    tags: "plague doctor, necromancer, bone beak mask, wide-brimmed black hat with skull emblem, open black tattered coat over leather bandeau top, bare midriff, brass-buckled straps, black shorts, thigh-high boots, bare thigh gap, grimoire at belt, carved bone scythe, pale skin, dark aura",
    hairStyle: "long twin braids", pose: "standing, scythe planted point-down, both hands on the shaft" },
  highpriest: { name: "대주교", style: "healer", tier: 3, equip: ["staff","tome"],
    tags: "archbishop, tall white mitre with gold trim, strapless white and gold vestment gown, bare shoulders, backless, waist side cutouts, gold brocade mantle cape, white opera gloves, gold sun emblem pendant, ornate golden crozier staff, grimoire chained to belt, serene, prayer, falling golden light particles",
    hairStyle: "long straight hair", pose: "crozier staff held upright with both hands, head slightly bowed in prayer" },
  inquisitor: { name: "심판관", style: "mage", tier: 3, equip: ["tome","mace","sword"],
    tags: "mage, wide-brimmed flat-topped hat, long dark blue coat-robe with gold trim, deep cleavage cutout, side cutouts, crimson sash, high-slit skirt, bare thigh, crimson thigh strap, black gloves, gold-clasped grimoire held open, orange flames from pages, flanged mace at hip",
    hairStyle: "low braid over shoulder", pose: "standing, open grimoire held in one hand at chest level, other hand pointing forward in judgment, stern" },
  arhat: { name: "나한", style: "monk", tier: 3, equip: ["claw","staff"],
    tags: "martial artist monk, one-shoulder sleeveless ivory gi, orange trim, bare shoulder, cleavage, side cutouts, high-slit skirt, bare leg, red sash, bronze clawed gauntlets, large prayer beads, gold circlet, ringed staff on back, muscular, fighting stance, serene expression, golden halo",
    hairStyle: "high tight bun", pose: "one palm forward, other fist at hip" },
  fallenmonk: { name: "파계승", style: "monk", tier: 3, equip: ["claw","mace"],
    tags: "martial artist monk, tattered sleeveless black gi open off-shoulder over crimson bandeau, bare midriff, thigh wraps, bare thigh gap, iron clawed gauntlets, orange embers on fists, broken prayer beads, crimson sash, short cape, flanged mace at hip, muscular, fighting stance, wicked grin",
    hairStyle: "messy shoulder-length hair", pose: "clenched clawed fist raised, embers on gauntlet" },
  madgeneral_apex: { name: "멸망의 군신", style: "fighter", tier: 4, equip: ["greatsword","axe"],
    tags: "red and black military greatcoat worn open, gold epaulettes, spiked black pauldrons, steel bikini armor, bare midriff, black shorts, thigh-high greaves, bare thigh gap, gold horned circlet, colossal greatsword on shoulder, glowing orange cracks, battle axe on back, red aura, orange embers, wild grin",
    hairStyle: "wild long messy hair", pose: "colossal greatsword resting on shoulder" },
  madgeneral_abyss: { name: "혈기의 대원수", style: "tank", tier: 4, equip: ["axe","sword","shield"],
    tags: "massive crimson-edged battle axe, huge spiked round shield, black steel bandeau breastplate with gold trim, bare midriff, spiked pauldrons, tattered crimson commander cape, gold marshal medals, black shorts, bare thighs, thigh-high black greaves, horned open-faced helm, crimson battle aura, floating red embers, fierce grin",
    hairStyle: "long wild messy hair", pose: "battle axe resting on shoulder, round shield at side" },
  bloodfiend_apex: { name: "진혈군주", style: "fiend", tier: 4, equip: ["katana","claw"],
    tags: "vampire, pale skin, fangs, floor-length sleeveless black long coat with crimson embroidery, high collar, black leotard with cleavage cutout, bare thighs, thigh straps, crimson gem circlet, twin clawed gauntlets, long katana with glowing crimson blade, floating blood droplets, crimson aura, red glow",
    hairStyle: "long straight hair", pose: "standing, katana held horizontally in front at chest height, blade glowing" },
  bloodfiend_abyss: { name: "불사의 혈염귀", style: "fiend", tier: 4, equip: ["claw","greatsword"],
    tags: "vampire, pale skin, fangs, crimson-trimmed black bikini armor top, bare midriff, plate pauldrons, open tattered black long coat, black shorts, bare thighs, plate greaves, oversized clawed gauntlets wreathed in crimson flames, greatsword on back, broken shackles, horned circlet, crimson embers, red glow",
    hairStyle: "messy short hair", pose: "standing, clawed gauntlets raised at chest, fingers spread, greatsword strapped on back" },
  swordgod_apex: { name: "무한의 검성", style: "fighter", tier: 4, equip: ["katana","sword"],
    tags: "white and red military tailcoat worn open, gold epaulettes, white halter top with gold infinity emblem, cleavage, bare midriff, white high-slit skirt, bare thigh, golden halo, brown leather boots, katana with white glowing blade held level, golden afterimage blades, longsword at hip, golden particles",
    hairStyle: "long low ponytail", pose: "katana held out to the side, blade level" },
  swordgod_abyss: { name: "폐검의 수라", style: "rogue", tier: 4, equip: ["katana","dagger"],
    tags: "assassin rogue, tattered black hooded robe worn open, hood down, black bandage wrap top, bare midriff, high slit, bare thigh, crimson asura demon half mask, steel pauldron, broken katana held low, dagger at hip, broken blades on back, glowing crimson cracks, crimson-black aura, lean, sly",
    hairStyle: "long messy hair", pose: "broken katana held low at side" },
  skysplitter_apex: { name: "개천검제", style: "fighter", tier: 4, equip: ["greatsword","katana"],
    tags: "red military coat worn open, gold epaulettes, silver bikini-cut breastplate, bare midriff, silver pauldrons, imperial red cape, gold circlet, red asymmetric high-slit skirt, silver thigh-high greave, bare thigh, colossal greatsword held aloft one-handed, white glowing fracture lines, katana at hip, white light shards, commanding",
    hairStyle: "high topknot bun", pose: "greatsword held aloft one-handed" },
  skysplitter_abyss: { name: "만검의 벽", style: "tank", tier: 4, equip: ["greatsword","sword","shield"],
    tags: "zweihander greatsword in black scabbard, huge tower shield studded with broken sword blades, sleeveless silver breastplate, bare arms, blade-shaped pauldrons, tall steel collar, navy high-slit armored dress, bare thigh, silver vambraces, steel headband, white glowing sword runes on shield, faint silver aura, calm expression",
    hairStyle: "hime cut", pose: "hand on hilt of sheathed greatsword, tower shield planted" },
  dragoonlord_apex: { name: "창룡제", style: "lancer", tier: 4, equip: ["spear","axe"],
    tags: "spear warrior, gold-trimmed dragon scale breastplate with cleavage window, high-slit dark blue skirt, bare thigh, massive spear with dragon head blade held upright, orange flames along spearhead, battle axe at hip, gold horned crown, crimson cape, dragon wing pauldrons, orange ember particles",
    hairStyle: "hime cut", pose: "standing, spear held upright, flames flickering along the blade" },
  dragoonlord_abyss: { name: "불멸의 기수", style: "tank", tier: 4, equip: ["spear","shield"],
    tags: "long spear with attached war banner, crimson banner flag, kite shield with golden dragon emblem, gold dragon-scale breastplate with cleavage cutout, bare midriff, dragon-wing pauldrons, crimson high-slit battle skirt, gold scaled thigh-high greaves, dragon-crest gold circlet, glowing gold scale accents, floating orange embers, stalwart",
    hairStyle: "side ponytail", pose: "banner spear held upright, kite shield at side" },
  skylancer_apex: { name: "뇌신창제", style: "lancer", tier: 4, equip: ["spear","wand"],
    tags: "spear warrior, silver-steel breastplate with gold engravings over sleeveless dark blue bodysuit with side cutouts, bare thighs, silver thigh plates, twin winged pauldrons, oversized spear crackling with white-gold lightning held upright, second spear on back, wand at belt, gold thunder crown, white cape",
    hairStyle: "long twin tails", pose: "standing, spear held upright, lightning arcing around it" },
  skylancer_abyss: { name: "천풍의 성창", style: "lancer", tier: 4, equip: ["spear","staff"],
    tags: "spear warrior, silver-steel breastplate over off-shoulder dark blue top with sheer white sleeves, bare midriff, flowing dark blue high-slit sarong, bare thigh, holy spear with glowing golden blade held upright, staff strapped on back, white wind swirls around spear, gold halo circlet",
    hairStyle: "low braid over shoulder", pose: "standing, spear held upright, wind swirling around it" },
  gatewarden_abyss: { name: "불괴의 세계문", style: "tank", tier: 4, equip: ["spear","shield"],
    tags: "iron spear, enormous gate-shaped iron tower shield, heavy chains draped across shield, strapless iron-grey corset breastplate, bare shoulders, gold keyhole emblem on chest, short iron-plated skirt, bare thighs, heavy iron sabatons, open-faced barbute helm, white glowing rune seals on shield, faint white aura, stalwart",
    hairStyle: "twin braids", pose: "gate shield planted squarely in front, spear held upright behind it" },
  gatewarden_apex: { name: "철문의 패왕", style: "tank", tier: 4, equip: ["spear","axe","shield"],
    tags: "massive iron spear, battle axe strapped on back, heavy square iron shield, halter-neck black iron breastplate, bare shoulders, bare midriff, black fur mantle, tall gold-spiked black iron crown, iron-plated black shorts, bare thighs, knee-high sabatons, orange glowing cracks across armor, domineering grin, stalwart",
    hairStyle: "slicked-back short hair", pose: "spear held forward, square shield at side" },
  reaper_apex: { name: "사신군주", style: "rogue", tier: 4, equip: ["scythe","dagger"],
    tags: "assassin rogue, long black hooded cloak, hood down, white skull half mask, black high-slit dress, bare leg, deep cleavage, dark pauldrons, bare shoulders, gold clasps, ornate black scythe with crimson blade held upright, dagger at thigh, black smoke wisps, glowing crimson accents, lean, sly",
    hairStyle: "hime cut", pose: "scythe held upright" },
  reaper_abyss: { name: "혼백의 수확자", style: "fiend", tier: 4, equip: ["scythe","shield"],
    tags: "vampire, pale skin, fangs, open crimson-lined black long coat, hood down, crimson leather corset top, cleavage, high-slit black skirt, bare thigh, thigh-high boots, plate pauldrons, tower shield, giant scythe with crimson-glowing blade, crimson soul wisps, chained ledger, red glow",
    hairStyle: "long wavy hair", pose: "standing, scythe held upright in right hand, tower shield on left arm" },
  paladin_apex: { name: "광휘의 성왕", style: "tank", tier: 4, equip: ["sword","mace","shield"],
    tags: "radiant longsword, golden light flowing down blade, tall heater shield with golden sun emblem, gold filigree breastplate with cleavage cutout, winged gold pauldrons, white high-slit gown, bare thigh, gold thigh-high armored boots, long white cape, golden crown, golden halo, floating gold light particles",
    hairStyle: "crown braid updo", pose: "longsword held upright at chest, heater shield at side" },
  paladin_abyss: { name: "성역의 수호성인", style: "oath", tier: 4, equip: ["mace","shield","tome"],
    tags: "holy paladin, saint, gold halo, white gold-filigree breastplate, cleavage cutout, bare shoulders, sheer white detached sleeves, gauntlets, long white high-slit skirt, bare thighs, armored greaves, large golden-glowing flanged mace, gold cross tower shield, floating grimoire, golden light ring, golden particles, serene",
    hairStyle: "hime cut", pose: "standing, tower shield planted upright, flanged mace resting on shoulder" },
  blackknight_apex: { name: "암흑의 폐왕", style: "fighter", tier: 4, equip: ["greatsword","axe"],
    tags: "black plate bikini armor, glowing crimson seams, jagged gold-trimmed pauldrons, tattered red military coat worn open, gold epaulettes, broken black crown, bare midriff, black tasset skirt, thigh-high greaves, bare thigh gap, crimson-runed greatsword held one-handed, battle axe on back, black shadow aura, crimson particles",
    hairStyle: "short slicked-back hair", pose: "greatsword held one-handed at side, other hand raised wreathed in black flames" },
  blackknight_abyss: { name: "영혼포식자", style: "fiend", tier: 4, equip: ["greatsword","scythe"],
    tags: "vampire, pale skin, fangs, black breastplate with glowing crimson seams, bare midriff, plate pauldrons, open crimson-lined black long coat, bare thighs, thigh straps, greaves, open-faced helm, crimson-runed zweihander greatsword, scythe on back, chains around arms, crimson soul flames, red glow",
    hairStyle: "low braid over shoulder", pose: "standing, greatsword planted point-down, both hands on hilt" },
  bulwark_abyss: { name: "부동의 대성벽", style: "tank", tier: 4, equip: ["mace","shield"],
    tags: "giant flanged mace, colossal wall-shaped stone-brick tower shield, sleeveless ultra-heavy steel breastplate, bare arms, bare midriff, crenellated slab pauldrons, stone-textured short faulds, bare thighs, steel sabatons, open-faced flat-top helm, anchor chains hanging from shield, white glowing rune lines across armor, white aura, immovable, stalwart",
    hairStyle: "long twin tails", pose: "wall shield planted, mace resting on top edge of shield" },
  bulwark_apex: { name: "분쇄의 거벽", style: "tank", tier: 4, equip: ["mace","axe","shield"],
    tags: "oversized flanged mace with battering-ram head, battle axe slung on back, bladed-edge tower shield, charcoal armored leotard with side cutouts, cracked copper breastplate, massive tower-like pauldrons, bare thighs, copper thigh-high greaves, red war paint on face, crimson glowing runes on mace, aggressive grin",
    hairStyle: "high bun", pose: "mace resting on shoulder, shield edge tilted forward" },
  oathshield_abyss: { name: "영원한 서약", style: "oath", tier: 4, equip: ["mace","shield","tome"],
    tags: "holy paladin, white armored leotard, gold cross, side cutouts, bare thighs, gold winged pauldrons, gold crown, long white cape, gauntlets, knee-high white boots, oversized golden-glowing flanged mace, heater shield with glowing gold oath sigil, chained spellbook, floating golden runes, golden aura, serene",
    hairStyle: "twin braids", pose: "standing, heater shield raised, flanged mace held high" },
  oathshield_apex: { name: "파약의 성기사", style: "tank", tier: 4, equip: ["sword","mace","shield"],
    tags: "longsword with crimson glowing oath runes, cracked kite shield with shattered sigil, off-shoulder torn white tabard-dress with high slit, tarnished gold breastplate, bare shoulders, bare thigh, broken chain dangling from gauntlet, tarnished gold thigh strap, half-broken gold circlet, black smoke-like aura, solemn expression",
    hairStyle: "cropped very short hair", pose: "longsword pointed downward, cracked shield held low" },
  masterarcher_apex: { name: "성락의 궁신", style: "archer", tier: 4, equip: ["bow","crossbow"],
    tags: "ranger archer, ornate white and gold leotard armor, cleavage cutout, gold pauldrons, bare thighs, gold thigh straps, brown cape, gold constellation emblem, golden star tiara, massive golden longbow, glowing golden arrow nocked, quiver of arrows, crossbow on back, golden aura, golden star particles",
    hairStyle: "hime cut", pose: "standing, longbow drawn, glowing arrow nocked" },
  masterarcher_abyss: { name: "천리의 풍궁수", style: "archer", tier: 4, equip: ["bow","staff"],
    tags: "ranger archer, tattered brown hooded cloak billowing, hood down, strapless silver-plated corset armor, bare shoulders, side cutouts, brown loincloth skirt, bare thighs, silver vambraces, tall silver longbow, floating arrows, quiver of arrows, silver staff on back, silver wind emblem, white wind aura",
    hairStyle: "high ponytail", pose: "standing, longbow held out to the side, arrows floating around" },
  shadowarcher_apex: { name: "공허의 사수", style: "rogue", tier: 4, equip: ["crossbow","dagger"],
    tags: "assassin rogue, ornate black cropped breastplate with silver trim, bare midriff, dark hood down, hollow white half mask, tattered dark cape, black thigh-high boots, bare thigh gap, ornate crossbow with glowing white bolt, dagger at thigh, silver arrow emblem, black particles, white glow, lean, sly",
    hairStyle: "side ponytail", pose: "crossbow held at hip aimed forward" },
  shadowarcher_abyss: { name: "망령 추적자", style: "archer", tier: 4, equip: ["crossbow","bow"],
    tags: "ranger archer, tattered dark brown hooded cloak, hood down, black leather harness top, cleavage, bare midriff, chain-wrapped bare arm, black short skirt, bare thighs, iron greaves, heavy black crossbow, glowing crimson bolt, quiver of arrows, longbow on back, black shadow wisps, crimson aura",
    hairStyle: "messy short hair", pose: "standing, crossbow held ready at chest level" },
  beastlord_apex: { name: "태초의 야왕", style: "monk", tier: 4, equip: ["claw","axe"],
    tags: "martial artist monk, open sleeveless crimson gi over bone bikini-style top, cleavage, bare midriff, pelt cape, fur loincloth, bare thighs, oversized clawed gauntlets, glowing orange runes, fang necklace, prayer beads, large battle axe on back, red aura, muscular, fighting stance, roaring",
    hairStyle: "very long wild mane-like hair", pose: "both clawed fists raised, chest out" },
  beastlord_abyss: { name: "만수의 대군주", style: "monk", tier: 4, equip: ["claw","axe","shield"],
    tags: "martial artist monk, bronze bikini-armor breastplate, cleavage, bare midriff, fur-lined pauldrons, antlered beast crown, orange wrap skirt, bronze greaves, bare thighs, clawed gauntlets, round bronze shield, prayer beads, battle axe at hip, golden tribal markings, golden aura, muscular, fighting stance",
    hairStyle: "long twin braids", pose: "shield raised, clawed fist ready" },
  spiritranger_apex: { name: "세계수의 궁성", style: "mage", tier: 4, equip: ["bow","staff","tome"],
    tags: "mage, crown of gold branches, off-shoulder dark blue robe dress with gold root-pattern embroidery, double high slits, bare thighs, sheer trailing sleeves, ivory bark bracers, long dark blue cape, gold-inlaid wooden longbow with white glowing bowstring, staff on back, white spirit wisps",
    hairStyle: "hime cut", pose: "standing, longbow held vertically at side, other hand lightly touching the glowing bowstring, serene" },
  spiritranger_abyss: { name: "정령의 화신", style: "healer", tier: 4, equip: ["bow","staff"],
    tags: "spirit avatar, white and gold leaf-embroidered bikini top, bare midriff, sheer white sarong skirt, bare thighs, glowing gold root tattoos, wooden antler circlet, bark brown bracers, ivory longbow carved like branches, gnarled wooden staff on back, floating golden leaves, white spirit motes, blessing",
    hairStyle: "long wavy hair", pose: "longbow held at side in one hand, other hand raised with floating golden leaves" },
  shadowblade_apex: { name: "밤의 군주", style: "rogue", tier: 4, equip: ["dagger","katana","claw"],
    tags: "assassin rogue, ornate sleeveless black hooded long coat, gold trim, hood down, deep V neckline, waist cutouts, gold crown, black half face mask, gold crescent moon emblem, clawed gauntlet, dagger held ready, katana sheathed at hip, glowing crimson lines, black shadow aura, lean, sly",
    hairStyle: "slicked-back long hair", pose: "dagger held forward, hand on katana hilt" },
  shadowblade_abyss: { name: "환영의 무영객", style: "rogue", tier: 4, equip: ["dagger","claw"],
    tags: "assassin rogue, black veiled hood, hood down, blank white noh half mask, form-fitting black off-shoulder top, silver trim, bare midriff, short black wrap skirt, thigh straps, bare thigh gap, oversized clawed gauntlets, dagger in reverse grip, black shadow wisps from gauntlets, silver glow, lean, sly",
    hairStyle: "long twin tails", pose: "dagger held in reverse grip, claw hand extended" },
  venomfang_apex: { name: "만독의 아왕", style: "rogue", tier: 4, equip: ["dagger","claw"],
    tags: "assassin rogue, gold-trimmed black scaled bikini armor top, black scaled high-slit skirt, bare thighs, thigh-high scaled boots, gold serpent pauldron, fanged gold crown, black fang half mask, clawed gauntlets, oversized dagger in each hand dripping black venom, crimson venom mist, glowing crimson accents, lean, sly",
    hairStyle: "high bun with loose strands", pose: "twin daggers held crossed" },
  venomfang_abyss: { name: "부식의 독왕", style: "fighter", tier: 4, equip: ["dagger","scythe"],
    tags: "corroded red military coat worn off one shoulder, tarnished gold epaulettes, bandage chest wrap, bare midriff, black corrosion veins, bronze beaked plague half-mask, black shorts, bandaged thighs, brown leather boots, dagger dripping black ooze, orange glowing edge, rusted scythe over shoulder, brown poison aura",
    hairStyle: "wavy shoulder-length hair", pose: "dagger held low, scythe over shoulder" },
  banditking_apex: { name: "암흑가의 패왕", style: "rogue", tier: 4, equip: ["axe","sword"],
    tags: "assassin rogue, luxurious black fur coat worn open, gold-inlaid black plate chest piece, cleavage cutout, gold crown, black face mask at chin, short black skirt, gold coin belt, bare thighs, gilded oversized battle axe held upright, longsword at hip, gold coin sparkles, lean, sly",
    hairStyle: "long wavy hair", pose: "battle axe resting on shoulder" },
  banditking_abyss: { name: "흑막의 대영주", style: "tank", tier: 4, equip: ["axe","sword","shield"],
    tags: "gilded battle axe, heater shield patched with stolen heraldry, brown fur-trimmed black overcoat worn open, black corset breastplate with gold inlay, deep cleavage, black shorts, bare thighs, black thigh-high boots, wide-brimmed black hat with crimson feather, gold coin chains, faint gold aura, smug expression",
    hairStyle: "side-swept long wavy hair", pose: "axe resting on shoulder, hand on hip" },
  bladedancer_apex: { name: "절검의 무성", style: "fighter", tier: 4, equip: ["dagger","katana"],
    tags: "off-shoulder cropped red bolero, gold epaulettes, single gold filigree pauldron, gold bikini-style dancer top, bare midriff, white silk streamers, long white double-slit skirt, bare thighs, gold anklet bells, brown leather dancer boots, dagger and katana crossed in front, blades glowing white, golden petal particles",
    hairStyle: "long twin tails", pose: "dagger and katana held crossed in front" },
  bladedancer_abyss: { name: "천무의 환영무희", style: "rogue", tier: 4, equip: ["dagger","katana"],
    tags: "assassin rogue, black silk crop top, bare midriff, black silk high-slit dancer skirt, silver bangles, bare arms, silver lower-face veil mask, dark hooded shawl, hood down, black silk ribbons, dagger in one hand, katana in the other, six black shadow wisps, silver particles, lean, sly",
    hairStyle: "long braided ponytail", pose: "dagger and katana held out to each side" },
  archmage_apex: { name: "허공의 마도제", style: "mage", tier: 4, equip: ["staff","tome","wand"],
    tags: "mage, wide-brimmed wizard hat with floating gold rings, floor-length dark blue robe with gold embroidery open over dark blue leotard, cleavage, bare thighs, black thigh-high stockings, gold pauldrons, tall gold-capped staff with huge orange glowing crystal, orbiting orange fireballs, floating grimoire",
    hairStyle: "long straight hair", pose: "standing, tall staff planted at side, free hand open with fireballs orbiting the palm, imperious" },
  archmage_abyss: { name: "만상의 현왕", style: "mage", tier: 4, equip: ["tome","staff"],
    tags: "mage, gold crown with floating gold rune halo, strapless floor-length dark blue robe with gold embroidery, bare shoulders, midriff cutout, gold chains, high slit, bare thigh, gold-clasped grimoire held open, white-gold glowing pages, white-gold rune circles, wooden staff on back",
    hairStyle: "twin braids", pose: "standing, grimoire held open in one hand at chest, other hand raised conducting glowing runes, composed" },
  stormcaller_apex: { name: "천뢰의 폭풍제", style: "mage", tier: 4, equip: ["wand","staff"],
    tags: "mage, wide-brimmed wizard hat with gold lightning emblem, dark blue bikini-style armor top, bare midriff, high-slit dark blue robe skirt with gold trim, gold pauldrons, tattered dark blue cape, gold wand with white glowing crystal, tall wooden staff, white-gold lightning arcs",
    hairStyle: "messy short hair", pose: "standing, wand in one hand and staff in the other, arms spread wide with lightning arcing between them" },
  stormcaller_abyss: { name: "폭풍의 성자", style: "healer", tier: 4, equip: ["staff","tome"],
    tags: "lightning saint, silver bikini armor breastplate, bare midriff, white and gold pauldrons, torn white cape, high-slit white battle skirt, thigh-high white armored boots, gold halo, ornate silver staff with gold lightning finial, floating open grimoire, crackling white-gold lightning arcs, glowing gold accents, fierce, prayer",
    hairStyle: "high ponytail", pose: "staff raised overhead in one hand, white-gold lightning arcing from the finial" },
  lichlord_apex: { name: "불사의 사령제", style: "necro", tier: 4, equip: ["staff","tome","scythe"],
    tags: "lich sovereign, necromancer, gold skull crown, bikini-style bone chestplate, bare midriff, skull pauldrons, gold-embroidered black tattered long skirt, double high slits, bone staff with glowing crimson skull, floating open grimoire, giant bone scythe on back, pale skin, glowing crimson runes, crimson aura",
    hairStyle: "hime cut", pose: "standing, staff held upright, other hand outstretched palm-up toward the floating grimoire" },
  lichlord_abyss: { name: "명계의 수호자", style: "necro", tier: 4, equip: ["tome","scythe"],
    tags: "soul warden, necromancer, ivory-trimmed backless black tattered halter gown, bare shoulders, high-low hem, bare thighs, silver circlet, silver chains across collarbone, open grimoire with glowing white pages, bone scythe on back, skull ornaments, pale skin, white soul flames, black aura",
    hairStyle: "low braid over shoulder", pose: "standing, grimoire held open in one hand, other hand raised with white soul flame" },
  plaguelord_apex: { name: "만역의 대군주", style: "necro", tier: 4, equip: ["scythe","tome"],
    tags: "plague sovereign, necromancer, horned bone half-mask, open high-collared black tattered mantle, leather leotard, bronze skull chest ornament, bare thighs, bone thigh straps, thigh-high boots, grimoire at belt, huge double-bladed bone scythe, pale cracked skin, glowing crimson cracks, black miasma aura",
    hairStyle: "messy short hair", pose: "standing, scythe resting on shoulder, one hand outstretched trailing miasma" },
  plaguelord_abyss: { name: "부패의 거체", style: "fiend", tier: 4, equip: ["scythe","mace"],
    tags: "vampire, pale skin, fangs, off-shoulder tattered black long coat, crimson-stained hem, bandage-wrap top, bare midriff, torn skirt, bare thighs, oversized bone pauldrons, bone mask on forehead, huge rusted scythe, flanged mace at hip, black smoke aura, red glow",
    hairStyle: "hime cut", pose: "standing, scythe resting on shoulder, mace hanging at hip" },
  highpriest_abyss: { name: "성좌의 교황", style: "healer", tier: 4, equip: ["staff","tome"],
    tags: "pontiff, towering gold papal tiara, floor-length white and gold halter gown, plunging neckline, sheer navy star-patterned side panels, thigh-high slit, bare leg, huge gold mantle collar, long gold chains, twin-orbed ornate golden staff, floating star-studded grimoire, halo of golden stars, glowing gold particles, serene, prayer",
    hairStyle: "hime cut", pose: "staff planted upright at side with one hand resting on it, other hand raised in benediction" },
  highpriest_apex: { name: "전쟁의 대사제", style: "mage", tier: 4, equip: ["mace","staff","tome"],
    tags: "mage, tall gold mitre, sleeveless dark blue vestment robe with gold trim, deep cleavage cutout, high slit, bare thigh, white stole with gold sun emblem, gold pauldrons, gold bracers, large gold flanged mace with glowing white-gold head, wooden staff on back, golden light halo",
    hairStyle: "side ponytail", pose: "standing, flanged mace raised upright in one hand, other hand in a blessing gesture, solemn" },
  inquisitor_apex: { name: "대심문관", style: "mage", tier: 4, equip: ["tome","sword","mace"],
    tags: "mage, hood down, gold half-mask, long dark blue coat-robe with gold trim, crimson lining, open over black bikini-style top, bare midriff, dark blue shorts, bare thighs, crimson thigh straps, black gauntlets, massive chained grimoire, orange flames from pages, longsword at hip",
    hairStyle: "wavy shoulder-length hair", pose: "standing, chained grimoire held open at chest with flames rising, other hand resting on longsword hilt, menacing" },
  inquisitor_abyss: { name: "정화의 화신", style: "tank", tier: 4, equip: ["mace","sword","shield"],
    tags: "orange flaming flanged mace, tower shield with burning brazier emblem, sleeveless white tabard with red cross, hood down, bare arms, cropped blackened steel breastplate, bare midriff, high-slit tabard skirt, bare thigh, blackened steel gauntlets and greaves, orange flames rising from gauntlets, stern expression",
    hairStyle: "low ponytail", pose: "flaming mace raised, tower shield planted" },
  arhat_apex: { name: "무극의 투신", style: "monk", tier: 4, equip: ["claw","staff"],
    tags: "martial artist monk, sleeveless white leotard gi, gold trim, cleavage cutout, backless, bare legs, red sash, golden clawed gauntlets, giant prayer beads, golden halo, ringed staff held upright, spectral golden hands behind, golden ki aura, muscular, fighting stance, serene expression",
    hairStyle: "long straight hair", pose: "staff held upright, other palm open forward" },
  arhat_abyss: { name: "금강불괴", style: "monk", tier: 4, equip: ["claw","staff","mace"],
    tags: "martial artist monk, sleeveless orange gi open to waist over chest wraps, cleavage, bare midriff, short hakama, high side slits, bare thighs, bronze metallic skin, glowing golden cracks, steel clawed gauntlets, massive prayer beads, ringed staff on back, iron collar, muscular, fighting stance",
    hairStyle: "short slicked-back hair", pose: "arms crossed, rooted stance" },
  fallenmonk_apex: { name: "아수라 파계존", style: "monk", tier: 4, equip: ["claw","mace"],
    tags: "martial artist monk, cropped sleeveless black gi, cleavage cutout, bare midriff, short skirt, thigh-high boots, bare thigh gap, glowing crimson clawed gauntlets, spectral shadow arms, asura mask on head, broken prayer beads, flanged mace at hip, crimson aura, muscular, fighting stance",
    hairStyle: "wild spiky short hair", pose: "clawed hands spread wide at sides" },
  fallenmonk_abyss: { name: "업화의 대존자", style: "monk", tier: 4, equip: ["claw","mace"],
    tags: "martial artist monk, blackened iron breastplate over sleeveless crimson gi, cleavage, bare midriff, pauldrons, molten orange cracks, high-slit crimson skirt, bare thigh, greaves, orange flaming clawed gauntlets, burning prayer beads, huge flanged mace on shoulder, torso chains, crimson cape, muscular, fighting stance",
    hairStyle: "short bob", pose: "mace resting on shoulder, fist clenched" },
};
